Chainlit/chainlit

src/chainlit/frontend/src/components/Code.tsx
src/chainlit/frontend/src/components/button.tsx
src/chainlit/frontend/src/components/chat/history/button.tsx
src/chainlit/frontend/src/components/chat/message/time.tsx
src/chainlit/frontend/src/components/chat/message/uploadButton.tsx
src/chainlit/frontend/src/components/element/frame.tsx
src/chainlit/frontend/src/components/slider.tsx
src/chainlit/frontend/src/components/tasklist/Task.tsx
src/chainlit/frontend/src/components/tasklist/TaskStatusIcon.tsx
src/chainlit/frontend/src/theme.ts

- add a loading animation to running tasks
- fix TaskStatusIcon alignment
- also refactored colors to use the color palette

improved the Task list component

---

src/chainlit/lc/agent.py
src/chainlit/lc/callbacks.py
src/chainlit/message.py
src/chainlit/server.py

Stream final answer

---

cypress/e2e/action/spec.cy.ts
src/chainlit/frontend/src/components/action/ref.tsx
src/chainlit/message.py

- also moved from action id to class to avoid duplicate IDs
- updated the tests to verify the action order

fix: send actions sequentially to guarantee order

---

src/chainlit/frontend/src/components/tasklist/Task.tsx
src/chainlit/frontend/src/theme.ts

fix: fixed the primary contrast text color

---

src/chainlit/frontend/src/App.tsx
src/chainlit/frontend/src/pages/Design.tsx

The purpose of this PR is to create a page that consolidates all existing UI components. 
Actually, I've just added the new designed one. In the near future, we'll add all of them.

Add design page on dev mode

---

src/chainlit/frontend/package-lock.json
src/chainlit/frontend/package.json
src/chainlit/frontend/src/components/atoms/element/sideView.tsx
src/chainlit/frontend/src/components/organisms/chat/index.tsx
src/chainlit/frontend/src/pages/Conversation.tsx

Purpose of this PR is to put the side view components to a drawer, wich will add a better UI when elements is showed and fix the responsive for mobile users.
https://github.com/Chainlit/chainlit/assets/18298759/f8be3608-7858-4584-b26b-908b7c404c71

Put side view into a drawer

---

src/chainlit/frontend/src/components/atoms/element/sideView.tsx

Fix warning isSmallScreen

---

src/chainlit/config.py
src/chainlit/frontend/index.html
src/chainlit/frontend/src/theme.ts
src/chainlit/server.py

Purpose of this PR is to let user custom UI colors, fonts, etc... via the config.toml

Inject theme settings to custom UI

---

src/chainlit/frontend/src/components/atoms/element/sideView.tsx

Fix https://github.com/Chainlit/chainlit/pull/180#issuecomment-1646775466

Fix side view may block chat submit button

---

src/chainlit/socket.py

fix load_chainlit_initial_headers error, add NULL check

Update socket.py fix load_chainlit_initial_headers error

---

src/chainlit/frontend/src/components/molecules/settingsModal.tsx

Before : <img width="438" alt="Capture d’écran 2023-08-02 à 11 51 50" src="https://github.com/Chainlit/chainlit/assets/18298759/7b86dced-7e55-445a-a324-902ef3c03f3d">
After : <img width="483" alt="Capture d’écran 2023-08-02 à 11 50 47" src="https://github.com/Chainlit/chainlit/assets/18298759/79ab10ce-952e-45c0-b828-5b290ebabb8c">

Fix settings modal

---

src/chainlit/frontend/src/components/organisms/chat/history/button.tsx

fix: anchorEl warning

---

cypress/e2e/llama_index_cb/main.py
src/chainlit/context.py
src/chainlit/llama_index/__init__.py
src/chainlit/llama_index/callbacks.py
src/pyproject.toml

Fix LlamaIndexCallbackHandler

---

src/chainlit/langchain/callbacks.py
src/chainlit/prompt.py

Langchain callback handler was not support placeholder messages (typically used for chat history)
https://github.com/Chainlit/chainlit/issues/316

add support for messages placeholder

---

.github/CONTRIBUTING.md
cypress/e2e/prompt_playground/provider.py
cypress/e2e/prompt_playground/spec.cy.ts
src/chainlit/frontend/src/components/organisms/FormInput.tsx
src/chainlit/frontend/src/components/organisms/playground/editor/completion.tsx
src/chainlit/frontend/src/components/organisms/playground/index.tsx
src/chainlit/frontend/src/components/organisms/playground/modelSettings.tsx
src/chainlit/input_widget.py
src/chainlit/langchain/callbacks.py
src/chainlit/playground/config.py
src/chainlit/playground/provider.py
src/chainlit/playground/providers/__init__.py
src/chainlit/playground/providers/huggingface.py
src/chainlit/playground/providers/langchain.py
src/chainlit/types.py

- Adding it automatically avoid the need for configuration
- Because the provider list is now dynamic, we need to update the llm provider list in the frontend
- There are no inputs in the automated providers yet

Automated prompt playground langchain llm provider

---

backend/chainlit/config.py
backend/chainlit/message.py
cypress/e2e/hide_prompt_playground/.chainlit/config.toml

- Create `features` config table
- Move existing `UI.show_prompt_playground` to `features.prompt_playground`
- run the `e2e/hide_prompt_playground` test

Add feature flags in config

---

frontend/src/App.css
frontend/src/components/organisms/chat/welcomeScreen.tsx

apply md css to chainlit.md and force md and set image max width

---

libs/components/src/auth/ProviderButton.tsx

- Handle special case for Microsoft Account UI
- Capitalize provider name

Add additional oauth providers

---

libs/components/package.json
libs/components/pnpm-lock.yaml
libs/components/src/auth/AuthLogin.tsx
libs/components/src/auth/ProviderButton.tsx

https://github.com/Chainlit/chainlit/assets/10745953/a1b6db89-3b2b-469f-bb06-fb962249ac1b
⚠️ The issue during signin is fixed on the be
- Use `react-password-checklist` to display password validation
- Reset error display on switching form
- Fix display of microsoft provider button
- Go to signup form
- Notice the password creation flow
- Notice that you can still login normally

Auth0 inspired UX

---

.github/CONTRIBUTING.md

- Add the section on how to develop the libs/components

Update contributing md to include lib/components

---

backend/chainlit/server.py

Fix custom logo import

---

backend/chainlit/oauth_providers.py

fix URL of MS Graph API for getting currently logged-in user after Azure AD OAuth

---

backend/chainlit/playground/providers/vertexai.py

Minor fix to resolve the async calls for the VertexAI provider in the LLM Provider.

fix(llm-playground): minor fix on the vertexai provider 

---

libs/components/src/playground/chat.tsx

[Prompt Playground] Don't show scrollbars if not needed

---

frontend/src/components/organisms/header.tsx

https://github.com/Chainlit/chainlit/assets/18298759/74de7022-c92b-4843-8987-b8e34b22c19c

feat: Add logo on header

---

README.md

This commit makes the following changes to the demo code in the Langchain documentation:
* Adds documentation comments to make the code more readable and easier to understand.
* Makes the `main()` function a separate function, which makes it easier to test and reuse.
* Overall, makes the code more modular and well-documented.

Update demo.py in README

---

cypress/e2e/cloud/.chainlit/config.toml
cypress/e2e/cloud/main.py
cypress/e2e/cloud/spec.cy.ts
cypress/support/testUtils.ts
frontend/src/components/organisms/conversationsHistory/sidebar/index.tsx

- Create new "cloud" test case
- Add Cypress test for conversations cloud feature
- `pnpm run test` should pass
- What is being tested?
- Authenticate app user
- Fetch conversation history
- Access historic conversation
- Delete historic conversation

Test chat history feature

---

backend/chainlit/oauth_providers.py

- Microsoft api doesn't return a url, so we need to base64-encode the returned png
- use the 48px image to minimize the base64 string
https://github.com/Chainlit/chainlit/assets/494686/b174e292-cdda-42bd-91b1-f9f89656d460

fix: add missing profile picture to azure oauth users

---

backend/chainlit/oauth_providers.py

- Introduced the `OAUTH_OKTA_AUTHORIZATION_SERVER_ID` environment variable
- There are two setups available in Okta, and they weren't taken into consideration in the OAuth provider
- When using a "Single Sign-On to Okta" setup, you need to set the `OAUTH_OKTA_AUTHORIZATION_SERVER_ID` environment variable to `false`
- When using Okta as the identity platform for your app or API, either set the `OAUTH_OKTA_AUTHORIZATION_SERVER_ID` environment variable to `default` if you have a developer account, or set it to the authorization server id from your Custom Authorization Server.

fix: Enable any Okta setup in the OAuth provider

---

libs/components/package.json
libs/components/pnpm-lock.yaml

Fixes a false positive security warning.

fix: upgrade password checker to remove the styled-components sub-library

---

backend/chainlit/playground/config.py
backend/chainlit/playground/providers/__init__.py
backend/chainlit/playground/providers/vertexai.py
backend/pyproject.toml

Add [Gemini](https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/gemini) Pro from GCP in the LLM Playground

feat(playground): Add Gemini Pro in the LLM playground

---

backend/chainlit/oauth_providers.py

Tested with my own Amazon Cognito instance #540

added Amazon Cognito OAuth provider

---

backend/chainlit/haystack/callbacks.py

I probably need to adjust this this so that there is a toggle turn streaming on and off, but just wanted to get an idea as to whether or not the way I implemented the code is in line with what you would typically be looking for. What I found is basically that Haystack does stream tokens, but it just doesn't have any obvious implementation for capturing the final answer as a stream (at least not for < 2.0). I played around with this locally and managed to get this to work, although I did notice a few differences between my version and the current main branch (which I adjusted for).
In short:
1. Is this a feature you would be interested in merging?
2. Are there any tests I have to put in place before something like this could be merged?
3. Are there any code style changes or implementation …

Adding streaming functionality to output for haystack callback manager

---

frontend/src/components/organisms/header.tsx
frontend/src/components/organisms/threadHistory/sidebar/OpenThreadListButton.tsx
frontend/src/components/organisms/threadHistory/sidebar/TriggerButton.tsx
frontend/src/components/organisms/threadHistory/sidebar/index.tsx
frontend/src/pages/Page.tsx

New way to open the chat history 🎉
https://github.com/Chainlit/chainlit/assets/18298759/a54161d9-dbe5-4588-9468-579123a1278a

refactor: Add new way to open chat history

---

libs/react-components/src/messages/MessageContainer.tsx

Add a button to auto scroll down :
https://github.com/Chainlit/chainlit/assets/18298759/129f9e53-a615-43fa-97b6-06a1aca8921f

feat: Add button to auto scroll down

---

frontend/package.json
frontend/src/components/molecules/tasklist/TaskList.tsx
libs/react-client/src/api/hooks/api.ts

Fix issues : https://github.com/Chainlit/chainlit/issues/667

fix: Tasklist flick

---

backend/pyproject.toml

Fixing Regular Expression Denial Of Service (ReDoS) Vulnerability using python-multipart 0.0.6

---

backend/chainlit/data/__init__.py

fix: fix typing for data layer

---

backend/chainlit/translations/de.json
backend/chainlit/translations/en-US.json
frontend/src/components/organisms/threadHistory/sidebar/ThreadList.tsx

added missing translation for time grouped categories shown in the chainlit UI:
'Today',
'Yesterday',
'Previous 7 days',
'Previous 30 days'

added missing translation for time grouped categories

---

backend/chainlit/markdown.py
backend/chainlit/server.py
cypress/e2e/readme/chainlit_pt-BR.md
cypress/e2e/readme/main.py
cypress/e2e/readme/spec.cy.ts

Release 1.0.200 includes language dependent interface. However, the readme provided by chainlit.md is still language agnostic.
This PR provides support for language dependent readme markdowns

Loads markdown file based on language

---

frontend/src/components/molecules/auth/ProviderButton.tsx

Fix typo in provider name

---

backend/chainlit/translations/de.json
backend/chainlit/translations/en-US.json
backend/chainlit/translations/pt-BR.json
frontend/src/components/molecules/settingsModal.tsx
frontend/src/components/organisms/chat/history/index.tsx

Add translations for untranslated ui items

add missing translation keys

---

backend/chainlit/data/sql_alchemy.py

Fixing 2 bugs: 
- adding `self.storage_provider = None` in `def __init__()` so that it does not break method create_element. 
- adding generation parameter in create_step as it's also a JSON type

Fix SQLAlchemyDataLayer in sql_alchemy.py

---

CHANGELOG.md
backend/pyproject.toml

PR containing the changelog updates and version bump.

release 1.0.506

---

backend/chainlit/discord/app.py

Bot will show as typing while the run is running.  Provides user feedback that something is happening.

feat: wrap on_message with typing

---

backend/chainlit/translations/zh-CN.json

i18n supplementary Chinese translation files

---

backend/pyproject.toml

Fixes pre-commit hook, closes #1195.

Ignore missing type stubs in Azure datalake.

---

.github/CONTRIBUTING.md
.github/workflows/mypy.yaml
.github/workflows/publish.yaml
.github/workflows/tests.yaml
backend/poetry.lock
backend/pyproject.toml

Add dev deps group and add isort and black there. Closes #1194 
Forked from #1192 as to allow for smooth merge/prevent merge conflicts.

Black isort as dev deps in pyproject.toml

---

backend/poetry.lock

Fixing dependency resolution. #1235 
So we have a strong basis for folks to fire PR's against.

Unbreak the build

---

backend/chainlit/llama_index/callbacks.py

#1178 Fix AttributeError: 'ChatCompletionChunk' object has no attribute 'get'

---

CHANGELOG.md

I'm proposing to start consistently applying semver and making this release 1.2.0 due to added functionality.

Changelog for version 1.2.0.

---

CHANGELOG.md

Correct 1.2.0 release date in changelog

---

.github/workflows/pytest.yaml
backend/poetry.lock
backend/pyproject.toml

Increase supported fastapi versions up until the latest version and run unit tests against all supported versions.

Test fastapi matrix

---

RELENG.md

Based on our conversation earlier today on release practices.

Documenting release engineering.

---

frontend/src/components/atoms/elements/Text.tsx

Corrected spelling error.
`occured` to `occurred`

Minor spelling error fix

---

frontend/src/components/molecules/messages/components/FeedbackButtons.tsx

fix: negative feedback class incorrect

---

CHANGELOG.md
RELENG.md
backend/pyproject.toml

Release prep 1.2.0

---

.github/CONTRIBUTING.md
README.md

Fix some markdownlint warnings and some consistency improvements.

Markdownlint fixes

---

.github/actions/pnpm-node-install/action.yaml
.github/actions/poetry-python-install/action.yaml
.github/workflows/ci.yaml
.github/workflows/e2e-tests.yaml
.github/workflows/mypy.yaml
.github/workflows/publish.yaml
.github/workflows/pytest.yaml
pnpm-workspace.yaml

Some improvements to the yaml files.

Yaml fixes

---

backend/chainlit/data/sql_alchemy.py
backend/poetry.lock
backend/pyproject.toml
backend/tests/conftest.py
backend/tests/data/conftest.py
backend/tests/data/test_sql_alchemy.py

Solve #1345 
_P.S._ mypy is annoying

1.2.0 Hotfix - Add get_element() to sql_alchemy.py

---

backend/chainlit/server.py
backend/tests/test_server.py

Allow spaces in avatar filenames. Fixes #1370.

---

frontend/src/components/molecules/tasklist/TaskList.tsx

#1408 minus irrelevant code. Facilitates backporting.

Fix tasklist when chainlit is submounted. Closes #1400. 

---

backend/chainlit/auth.py
backend/chainlit/cache.py
backend/chainlit/cli/__init__.py
backend/chainlit/context.py
backend/chainlit/discord/__init__.py
backend/chainlit/server.py
backend/chainlit/slack/__init__.py
backend/chainlit/step.py
backend/chainlit/teams/__init__.py
backend/tests/test_callbacks.py
cypress/e2e/action/main.py

Pending adoption of clear and strict formatting standards for the project, this is @EWouters's PR minus formatting and ordering of imports (and, as a result, minus merge conflicts).

Fixes from EWouters:python-fixes-2 minus formatting

---

backend/chainlit/auth.py
backend/chainlit/config.py

Addresses #1031
This adds `user_session_timeout` variable to config.toml to make user session timeout configurable.

feat: Add configurable user_session_timeout

---

CHANGELOG.md
backend/pyproject.toml

Release prep 2.0.dev1

---

CHANGELOG.md
backend/chainlit/server.py
backend/pyproject.toml

Hotfix release as discussed. This PR is for the 1.3 release branch.

Release prep for 1.3.1

---

CHANGELOG.md
backend/pyproject.toml

Dokterbob/release prep 1.3.1

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
backend/README.md
package.json

Fixups for new Python-leading package build.

Build fixups

---

cypress.config.ts
cypress/support/testUtils.ts

There was an intermittent error in E2E tests which _should_ be resolved with this patch. (If not, at least it won't hurt -- might even slightly increase performance.)

Fixup in E2E tests

---

backend/chainlit/data/__init__.py

* Initialise data layer only once (closes #1465).
* Give DeprecationWarning when users set `_data_layer` directly.
* Remove debug print statement.

Various tweaks to data_layer acquisition logic.

---

backend/chainlit/config.py

Fix forward annotations evaluation issue in `chainlit.config`

---

backend/chainlit/translations/en-US.json
frontend/src/components/AutoResizeTextarea.tsx
frontend/src/components/CodeSnippet.tsx
frontend/src/components/chat/MessageComposer/index.tsx

Fixing https://github.com/Chainlit/chainlit/issues/1631.

fix: raw block code

---

frontend/src/components/ChatSettings/TextInput.tsx

Fixing https://github.com/Chainlit/chainlit/issues/1642

fix: text input value should update

---

frontend/src/components/chat/MessageComposer/UploadButton.tsx

Fixing https://github.com/Chainlit/chainlit/issues/1641

fix: attachment should not show if not enabled

---

libs/copilot/index.tsx
libs/copilot/src/app.tsx
libs/copilot/src/widget.tsx

Fixing https://github.com/Chainlit/chainlit/issues/1638

feat: add function on window to toggle the copilot

---

backend/chainlit/server.py

Fixing https://github.com/Chainlit/chainlit/issues/1636

fix: actions should trigger first_interaction

---

frontend/src/components/ChatSettings/index.tsx

Fixing https://github.com/Chainlit/chainlit/issues/1659

fix: make chat settings modal scroll if too tall

---

backend/chainlit/translations/bn.json
backend/chainlit/translations/en-US.json
backend/chainlit/translations/gu.json
backend/chainlit/translations/he-IL.json
backend/chainlit/translations/hi.json
backend/chainlit/translations/kn.json
backend/chainlit/translations/ml.json
backend/chainlit/translations/mr.json
backend/chainlit/translations/nl-NL.json
backend/chainlit/translations/ta.json
backend/chainlit/translations/te.json
backend/chainlit/translations/zh-CN.json
frontend/src/components/CopyButton.tsx

This pull request includes updates to the translation files for multiple languages and improvements to the `CopyButton` component in the frontend.

feat: add translation on copy bottun

---

backend/chainlit/translations/ja.json

add json file to translate into japanese

---

frontend/src/components/Elements/ElementRef.tsx

feat: improve element ref styling

---

backend/chainlit/auth/cookie.py

Fixing https://github.com/Chainlit/chainlit/issues/1711

fix: use config value for cookie max age

---

backend/chainlit/emitter.py
frontend/src/components/chat/Messages/Message/AskFileButton.tsx

Fixing https://github.com/Chainlit/chainlit/issues/1724

fix: match file id with element id

---

libs/react-client/src/utils/group.ts

The current implementation has potential timezone issues and inconsistent grouping due to:
1. Date Boundary Issues
- Using `toDateString()` for comparison makes grouping sensitive to specific time
- Example: A thread created at "2024-01-17 23:59 UTC" might show in different groups for users in UTC+8 vs UTC-8
2. Overlapping Group Logic
- Direct `>=` comparisons with `sevenDaysAgo` and `thirtyDaysAgo` can cause threads to appear in multiple groups
- Example: A thread from yesterday might also match `>= sevenDaysAgo` condition
3. Time Sorting
- Lacks time-based sorting within groups
- Leads to inconsistent thread ordering in UI
```typescript
// Before
const isToday = createdAt.toDateString() === today.toDateString();
// After
today.setHours(0, 0, 0, 0);
threadDate.setHours(0, 0, 0, 0);
const …
```

fix: optimize thread date grouping logic

---

frontend/tailwind.config.js

Resolves #1702. 
To replicate:
1. Install Node > 22
2. Build frontend: `pnpm buildUi`
3. On `main` -> fail
4. On `dokterbob/frontend_build_failures_exploration` -> success

fix: frontend build failures (closes #1702)

---

backend/chainlit/element.py

chore: update element.py

---

frontend/src/components/chat/index.tsx

fix: correct translator path

---

backend/chainlit/data/storage_clients/azure_blob.py

Fix for #1837 , Azure Blob SAS not using UTC.

fix: ensure SAS token start time is set to UTC

---

frontend/src/components/Elements/ElementRef.tsx

Remove 22px element ref height

---

backend/chainlit/oauth_providers.py

Modify offline_access to have fully qualified Microsoft graph prefix.
Fix for #1845

Update offline_access scope to be fully qualified with the prefix

---

frontend/src/components/chat/MessageComposer/Input.tsx

Fixing https://github.com/Chainlit/chainlit/issues/1854

fix: paste html

---

libs/react-client/package.json
libs/react-client/tsconfig.build.json
libs/react-client/tsconfig.json

chore: allow react-client to be built as dependencies

---

frontend/src/components/chat/MessageComposer/Input.tsx

Sort commands based on the start index of the included string

Replace command filter from startsWith to includes

---

backend/chainlit/oauth_providers.py

Removing prefix as it doesn't correctly get refresh_token.

Revert oauth_providers.py by removing prefix in offline_access

---

frontend/src/components/chat/MessageComposer/Input.tsx

Fixing https://github.com/Chainlit/chainlit/issues/1890

fix: input should not replace <,>,&

---

backend/chainlit/auth/cookie.py

fix: allow setting custom cookie name via env var

---

backend/chainlit/cli/__init__.py
backend/chainlit/server.py

Fixing https://github.com/Chainlit/chainlit/issues/1904

fix: attempt to fix root path in docker

---

frontend/src/components/chat/Messages/Message/AskFileButton.tsx
frontend/src/components/chat/index.tsx
libs/react-client/src/api/index.tsx

This patch allow to display the server error message correctly in the toast.

fix: When upload fail server side the error message was undefined front

---

CHANGELOG.md
backend/chainlit/config.py
frontend/src/components/chat/ScrollContainer.tsx
frontend/src/components/chat/index.tsx
libs/copilot/src/chat/body.tsx
libs/react-client/src/types/config.ts

Fixing https://github.com/Chainlit/chainlit/issues/1992

feat: add feature flag for user message auto scroll

---

frontend/src/components/ChatSettings/index.tsx

Fix: Chatsetting dialog padding is too small

---

frontend/src/components/chat/Messages/Message/Content/InlinedElements/InlinedPlotlyList.tsx

Fix Plotly width in #1919

---

backend/chainlit/langchain/callbacks.py

closing https://github.com/Chainlit/chainlit/issues/1940

feat: add thinking token support to lc

---

frontend/src/components/LeftSidebar/Search.tsx
frontend/src/components/LeftSidebar/ThreadHistory.tsx
frontend/src/components/chat/MessageComposer/index.tsx
frontend/src/components/chat/Starters.tsx
frontend/src/components/chat/WelcomeScreen.tsx
frontend/src/components/header/ApiKeys.tsx
frontend/src/components/header/SidebarTrigger.tsx
frontend/src/components/header/UserNav.tsx

This PR adds `id` attribute for most commonly customized ui elements. This will simplify customization, extensibility & testing

feat: add ids for most commonly customized ui elements

---

backend/chainlit/config.py
frontend/src/pages/Page.tsx
libs/react-client/src/types/config.ts

This PR introduces configuration option for default sidebar state and by so closes #1200
P.S. Commit in this PR was made without pre-commit checks because of #2064

feature: add configuration option for default sidebar state

---

frontend/src/components/chat/MessageComposer/Input.tsx

Remove insertText command to prevent duplicate pasting

---

frontend/src/components/chat/index.tsx

This ensures the copilot functions can also be executed in the main application. This is useful, if you want to further customize the experience.

Enable CopilotFunction for main application

---

backend/chainlit/data/storage_clients/s3.py

in case of using localstack, when man follows the official doc guide. The file is uploaded to the local s3 server, but the url here is hard coded, so the user can not download the file.

feat: s3 url should not be hard coded, when using localstack s3

---

backend/chainlit/server.py

It should allow lang codes like tzm-Latn-DZ
https://stackoverflow.com/questions/3191664/list-of-all-locales-and-their-short-codes

fix(server): follow the BCP 47 standard for the length of localization names

---

frontend/src/components/chat/MessageComposer/Input.tsx

This is another PR to fix #2326 after user clarified the issue is about sending HTML to the server, not pasting itself

fix: use built-in html unescaping to send html to the server

---

frontend/src/components/chat/MessageComposer/Input.tsx

Hopefully this is last one until we implement #2357 and get rid of such issues entirely.
Fixes #2367

fix: preserve new lines and indentation on paste

---

backend/chainlit/slack/app.py

feat: add threadId for user feedbacks sent from Slack

---

backend/chainlit/callbacks.py

fix: type hint for mcp functions

---

.github/workflows/copilot-setup-steps.yaml

This PR implements a GitHub workflow to optimize the development environment for GitHub Copilot's coding agent, following the official [GitHub documentation](https://docs.github.com/en/copilot/how-tos/use-copilot-agents/coding-agent/customize-the-agent-environment).
**NOTE:** Follow the [instructions here](https://docs.github.com/en/copilot/how-tos/use-copilot-agents/coding-agent/customize-the-agent-firewall) to add `cypress.io` to the agent firewall allow list so that Cypress can be downloaded and installed.
The new `.github/workflows/copilot-setup-steps.yaml` file pre-configures Copilot's ephemeral development environment with all necessary dependencies and build artifacts, eliminating the trial-and-error dependency discovery process that can be slow and unreliable.
- **Required …

Add copilot-setup-steps.yaml GitHub workflow for GitHub Copilot coding agent

---

frontend/src/api/index.ts

Headers are missing in the payload sent to the server

Add missing headers when connecting Streamable HTTP MCP

---

backend/chainlit/auth/__init__.py

fix: revert breaking change of custom auth

---

backend/chainlit/translations/zh-TW.json

Add zh-TW.json, which contains the Traditional Chinese translations used in Taiwan.

feat: add Traditional Chinese (Taiwan) translations
