CHANGELOG.md, cypress/e2e/ask_file/main.py, cypress/e2e/ask_file/spec.cy.ts, cypress/fixtures/hello.cpp, cypress/fixtures/hello.py, src/chainlit/frontend/src/components/chat/message/uploadButton.tsx, src/chainlit/frontend/src/state/chat.ts, src/chainlit/message.py, src/chainlit/types.py
Right now `AskFileMessage`'s accept parameter takes a list. For instance `["text/plain"]` will generate `{"text/plain": []}` in the UI.
The UI uses react dropzone, here is how it handles file type restrictions: https://react-dropzone.org/#!/Accepting%20specific%20file%20types
This approach is not allowing to filter on specific file types. For instance, if I only want to accept a python file, i need the following accept in react dropzone: `{"text/plain": [".py"]}`.
This PR enables `AskFileMessage`'s accept parameter to either take a list (for simplicity) or a dict for more detailed use cases.
=> AskFileMessage accept parameter can now take a dict

src/chainlit/server.py
The OpenAI completion api doesn't support an empty stop array, so we just get rid of the array in this case.
=> fix: prevent sending unsupported data to OpenAI

cypress.config.ts
This speeds up the CI (no video recording + no video compression), we can still enable the e2e video recording by reverting the flag locally.
Here is the comparison between [this PR run](https://github.com/Chainlit/chainlit/actions/runs/5145900989) and the [previous successful build](https://github.com/Chainlit/chainlit/actions/runs/5143544662) for the "Run tests" task:
- Ubuntu: from 7m 26s to 5m 47s (**1m 49s saved**)
- Windows: from 10m 49s to 9m 7s (**1m 42s saved**)
It's not a big win, but this changes removes some work from the CI so it's still a good thing.
=> perf: disable video on cypress tests by default

.github/CONTRIBUTING.md
Following my setup, here are some improvements to the contributing docs:
- A faster way to develop: with the addition of the `-e` flag in `pip install`, you don't need to run the `pip install` command every time you've made a change to the python source.
- Miscellaneous improvements (added missing `black` requirement, fixed an incorrect path, reworked the docs to focus on a full install, with an optional frontend-only and backend-only setup).
=> docs: improve the contributing instructions

src/chainlit/frontend/src/components/element/sideView.tsx
- Each new message sent was re-rendering the side view element
- Solved with only re-rendering the element when its content is changed
=> fix: prevent unneeded side view renderings

src/chainlit/frontend/src/components/chat/inputBox/input.tsx
When using an Japanese Input Method Editor (IME), the Enter key is used for finalizing character conversion. This conflicts with pressing the Enter key to submit form, and causes premature form submission and frustration for Japanese users who are in the middle of inputting text.
This PR ensures that the Enter key will only send the message if the user is not in the middle of an IME conversion, which should provide a more intuitive experience for users typing in Japanese.
NOTES: not sure but this might also happen in Chinese and Korean language which use IME.
- track whether the user is in the middle of an IME conversion by using the `compositionstart` and `compositionend` events
- modify `handleKeyDown` to only send the message if the Enter key is pressed and the user is not in the …
=> avoid premature form submission when using IME

.github/CONTRIBUTING.md
- Add guide to set a standard fork with two remote repositories
- Added a table of contents for easier doc consumption
=> docs: add fork instruction

.github/CONTRIBUTING.md
- We moved away from doing API calls, this removed the need from creating a .env file with a valid api key
=> docs: remove .env requirement for running tests

package.json, src/chainlit/frontend/babel.config.cjs, src/chainlit/frontend/jest.config.cjs, src/chainlit/frontend/package-lock.json, src/chainlit/frontend/package.json, src/chainlit/frontend/src/components/chat/message/content.spec.tsx, src/chainlit/frontend/src/components/chat/message/content.tsx
- Sorting by descending length helps avoiding matching substrings, because the longuest strings are searched first
before
after
=> fix: prevent substring matches in element links

src/chainlit/frontend/src/components/chat/message/content.tsx
- Prevents warning when messages contain a p, pre or div
=> fix: changed a parent tag from p to div

cypress/e2e/on_chat_start/main.py, cypress/e2e/on_chat_start/spec.cy.ts, src/chainlit/frontend/src/components/Code.tsx
- This splits the code highlighting code into a new chunk
- Speeds up initial loading, only loads code highlighting when needed
before
after
todo
=> perf: move prism to dynamic import

.github/CONTRIBUTING.md
There is no `buildUi` script in `/src/chainlit/frontend/package.json` so the commands to start UI in CONTRIBUTING.md will not work. Should run `buildUi` at repo root then cd into frontend folder.
=> fix commands order to start UI

.github/CONTRIBUTING.md, src/chainlit/frontend/src/api/index.ts
- Introduce a conditional instead of relying on modifying the source code
- Modify the contributing docs based on https://github.com/Chainlit/chainlit/pull/101
> By default, the dev server (dev command) runs in development mode and the build command runs in production mode.
Source: [Vite modes](https://vitejs.dev/guide/env-and-mode.html#modes)
This means that `import.meta.env.DEV` is:
- `true` when running `vite`
- `false` when running `vite build`
=> fix: get rid of the `serverUrl` manual change when developping

cypress/e2e/global_elements/spec.cy.ts, src/chainlit/element.py, src/chainlit/frontend/src/components/chat/message/content.spec.tsx, src/chainlit/frontend/src/components/chat/message/content.tsx, src/chainlit/frontend/src/components/tasklist/Task.tsx, src/chainlit/frontend/src/components/tasklist/types.d.ts, src/chainlit/frontend/src/state/chat.ts, src/chainlit/server.py
- Tasks can now have a `forId` property that contains a message `id` or `tempId`
- the chat scrolls to the linked message when clicking on a task
- the linked message is highlighted when clicking on a task
- fixed mime type for the tasklist
- fixed exiting chainlit when using make_async
=> feat: add jump to message from the tasklist

src/chainlit/frontend/src/components/dataset/filters/SearchBar.tsx
- This lowers the js asset size
- And slightly speeds up the build
Before
After
=> fix: only import the needed lodash submodule

src/chainlit/element.py
since avatar was overriding the default send, content was not sent to the UI. To avoid this, I now set content in to_dict
=> fix avatar using the path parameter

cypress/support/utils.ts, src/chainlit/__init__.py, src/chainlit/element.py, src/chainlit/telemetry.py
It looks like just initialising the telemetry object was causing networks ops, which is causing issues for users using secured enterprise network (uptrace is not allowed there).
=> ensure telemetry is NEVER called when disabled

src/chainlit/frontend/src/components/organisms/playground/index.tsx, src/chainlit/frontend/src/components/organisms/playground/modelSettings.tsx
Purpose of this PR is to place the model settings container into a drawer. Since it's useless to have it fixed, it will help to be more responsive. I have also reduced the text area height to fit to the user screen and show the submit button on first render.
https://github.com/Chainlit/chainlit/assets/18298759/4ff92d2a-71c5-4e3d-b501-c60add1db64d
=> Move model settings to drawer

src/chainlit/frontend/src/components/organisms/chat/message/content.spec.tsx, src/chainlit/frontend/src/components/organisms/chat/message/content.tsx
The following simple program containing scoped elements would not render the links correctly:
```python
import chainlit as cl
@cl.on_chat_start
async def main():
element1 = cl.Text(name="Document[1]", content="Testing", display="side")
element2 = cl.Text(name="Source(45)", content="Testing", display="side")
await cl.Message(
content=f"Testing: Document[1] or Source(45)", elements=[element1, element2]
).send()
```
I've added code that escapes regex characters so that the element names are matched correctly.
=> Fix for element names containing regex characters

src/chainlit/message.py
Currently the __init__ method initializes with a default empty list for both actions and elements.
However in Python an empty list as a default argument is only defined once and subsequent calls will return the same exact list.
This means that if you create a new Message it will be assigned the list of the previously created Message (if the elements property is not provided).
This PR fixes this problem.
The following program showcases the bug:
```python
import chainlit as cl
@cl.on_chat_start
async def main():
element1 = cl.Text(name="Document_1", content="Testing", display="side")
element2 = cl.Text(name="Document_2", content="Testing", display="side")
message1 = cl.Message(author="Agent", content="")
message1.elements.append(element1)
message1.elements.append(element2)
await …
```
=> Fix Message __init__

src/chainlit/server.py
`None` is not supported by JavaScript. We should replace it by `undefined` or the front won't set custom theme if there is one `None` value <img width="810" alt="Capture d’écran 2023-07-25 à 10 03 37" src="https://github.com/Chainlit/chainlit/assets/18298759/d17f15c2-a11d-4eba-aea5-993a0637241b">
=> Parse custom theme json before injecting it to front

src/chainlit/frontend/src/api/index.ts, src/chainlit/frontend/src/components/atoms/element/ref.tsx, src/chainlit/frontend/src/components/atoms/element/view.tsx, src/chainlit/frontend/src/components/organisms/chat/index.tsx, src/chainlit/frontend/src/components/organisms/chat/message/author.tsx, src/chainlit/frontend/src/components/organisms/chat/message/container.tsx, src/chainlit/frontend/src/components/organisms/chat/message/content.tsx, src/chainlit/frontend/src/components/organisms/chat/message/inlined.tsx, src/chainlit/frontend/src/components/organisms/chat/message/message.tsx, src/chainlit/frontend/src/components/organisms/chat/message/messages.tsx, src/chainlit/frontend/src/components/socket.tsx, src/chainlit/frontend/src/hooks/clearChat.ts, src/chainlit/frontend/src/state/chat.ts, src/chainlit/frontend/src/state/element.ts
I made some changes to the `element.ts` to make typescript smarter causing less `as` casts. 
I also separated Avatar and TaskList from the other elements so that you don't need to write logic to extract them from the other elements.
Open to any feedback!
=> Improve element type inference

src/chainlit/__init__.py, src/chainlit/chat_settings.py, src/chainlit/frontend/src/components/organisms/chat/settings.tsx, src/chainlit/frontend/src/state/chat.ts, src/chainlit/input_widget.py, src/chainlit/types.py
- One use case is for example configuring the list of stopwords for LLMs
- Also renamed "SelectInput" to "Select" as they are exposed throught "input_widget"
- Moved the ChatSettings in a separate file to enable using the input widgets outside of the chat settings
=> add a Tags input

src/chainlit/__init__.py, src/chainlit/chat_settings.py, src/chainlit/config.py, src/chainlit/emitter.py, src/chainlit/frontend/src/components/atoms/switch.tsx, src/chainlit/frontend/src/components/organisms/FormInput.tsx, src/chainlit/frontend/src/components/organisms/chat/index.tsx, src/chainlit/frontend/src/components/organisms/chat/inputBox/input.tsx, src/chainlit/frontend/src/components/organisms/chat/settings.tsx, src/chainlit/frontend/src/components/organisms/inputs/selectInput.tsx, src/chainlit/frontend/src/components/organisms/inputs/tagsInput.tsx, src/chainlit/frontend/src/components/organisms/slider.tsx, src/chainlit/frontend/src/components/socket.tsx, src/chainlit/frontend/src/hooks/clearChat.ts, src/chainlit/frontend/src/pages/Design.tsx, src/chainlit/frontend/src/state/chat.ts, src/chainlit/input_widget.py, src/chainlit/session.py, src/chainlit/socket.py, src/chainlit/types.py, src/chainlit/user_session.py
I've implemented a way to change chat settings so that a user is able to tweak LLM, Agent and other tool settings to their liking. To demonstrate, I used the image-gen cookbook example and adapted it to give the user more options to generate beautiful images (Looking forward to your feedback!):
<details>
<summary>Show Image 1 (512x512)</summary>
</details>
<details>
<summary>Show Image 2 (256x256)</summary>
</details>
<details>
<summary>Show Code app.py</summary>
```python
from langchain.agents import AgentExecutor, AgentType, initialize_agent
from langchain.agents.structured_chat.prompt import SUFFIX
from langchain.chat_models import ChatOpenAI
from langchain.memory import ConversationBufferMemory
from utils.tools import edit_image_tool, generate_image_tool
import chainlit as cl
from …
```
=> Implement chat settings

src/chainlit/frontend/src/components/molecules/inputLabel.tsx, src/chainlit/frontend/src/components/organisms/FormInput.tsx, src/chainlit/frontend/src/components/organisms/chat/settings.tsx, src/chainlit/frontend/src/components/organisms/inputs/selectInput.tsx, src/chainlit/frontend/src/components/organisms/inputs/tagsInput.tsx, src/chainlit/frontend/src/components/organisms/inputs/textInput.tsx, src/chainlit/frontend/src/pages/Design.tsx, src/chainlit/frontend/src/state/chat.ts, src/chainlit/frontend/tsconfig.json
This PR contains several changes:
- I changed the InputLabel id={id} to htmlFor={id} to make sure that the labels are linked to the inputs. I was unable to make it work using the id attribute. (Normally MUI does this for us using the id attribute, but this didn't work for some reason)
- Changes to FormInput as discussed to make sure that it is always in a controlled state (and won't switch to uncontrolled if passed null or undefined as a value)
- Some fixes to make sure that formik.handleChange works.
- I had to use formik.setField for the tagsInput since the mui-chips-input doesn't expose an onChange event handle. Not really happy about my solution since now tagsInput 'knows' about Formik. 
- I added 'strictNullChecks' to the tsconfig.json file and added a check to make sure that the …
=> FormInput improvements

.gitignore, src/chainlit/frontend/src/components/atoms/action/ref.tsx
When a disabled `Button` was provided to the `Tooltip` component, a mui warning will occur:
```txt
Tooltip.js:276 MUI: You are providing a disabled `button` child to the Tooltip component.
A disabled element does not fire events.
Tooltip needs to listen to the child element's events to display the title.
Add a simple wrapper element, such as a `span`.
```
Noted: This warning text display on development, not on production.
=> fix: mui warning on Tooltip component wrap a disabled Button

src/chainlit/frontend/src/components/organisms/chat/message/author.tsx
This PR fix the green line on indented message with parentId
=> fix: Display line on message with parentId

.gitignore, src/chainlit/frontend/package.json
The logs of the error:
```sh
$ cd src/chainlit/frontend/ && pnpm format
> chainlit-ui@0.0.1 format D:\projects\chainlit\src\chainlit\frontend
> prettier --config .prettierrc 'src/**/*.{ts,tsx}' --write --loglevel error
[error] No files matching the pattern were found: "'src/**/*.{ts,tsx}'".
 ELIFECYCLE  Command failed with exit code 2.
(venv)
```
=> fix: format command failed on windows

src/chainlit/langflow/__init__.py
As langflow changed the method input parameter name it needs to be adapted to make it work again.
See following change in langflow here: https://github.com/logspace-ai/langflow/commit/008a1c40791310105c653e2e479afc9f1da6f412
=> fix: Update langflow load_flow_from_json method input parameter

cypress/e2e/author_rename/main.py, cypress/e2e/haystack_cb/main.py, cypress/e2e/langchain_cb/main_async.py, cypress/e2e/langchain_cb/main_sync.py, cypress/e2e/llama_index_cb/main.py, src/chainlit/__init__.py, src/chainlit/utils.py
This keeps the imports fast, but with a few advantages over the current implementation:
1. we don't introduce a breaking change to the end users;
2. it's easier to import `chainlit` once and getting all things from there;
3. doing so also makes it easier to read the code and understand what comes from chainlit: `cl.LangchainCallbackHandler` makes it obvious that it's Chainlit's callback handler for Langchain (as opposed to `LangchainCallbackHandler`, without `cl.` in front).
=> Make callbacks available at the main module level again, but lazily

cypress/e2e/tasklist/main.py, cypress/e2e/tasklist/spec.cy.ts, src/chainlit/frontend/src/components/socket.tsx
- When splitting the frontend state for tasklists and avatars away from other elements, we introduced a but where it wasn't possible to remove the tasklist and avatars.
- Attempting to remove an element across the three existing element states (elements, tasklists, avatars) restores the feature.
=> fix: enable removing tasklists and avatars

src/chainlit/__init__.py
Only import expensive callback handlers modules for static type checkers, otherwise, these modules will be lazily imported at runtime through `__getattr__`.
=> Allows IDE autocompletion for callback handlers

src/chainlit/frontend/src/components/organisms/chat/message/content.tsx
=> ✨ add markdown table rendering support to enhance user experience when displaying tabular data in chat messages

src/chainlit/cache.py, src/chainlit/haystack/__init__.py, src/chainlit/langchain/__init__.py, src/chainlit/langflow/__init__.py, src/chainlit/llama_index/__init__.py, src/chainlit/utils.py, src/pyproject.toml
Fix version comparison from string compare to PEP 440 versions.
`packaging.version` is used instead of `semver` because `semver` doesn't support version like `0.8.11.post3`
=> Compare versions with packaging.version

cypress/e2e/llama_index_cb/main.py, src/chainlit/llama_index/callbacks.py, src/chainlit/sync.py
When using streaming, the main event loop is blocked to await tokens, if we try to execute a function (`Message.send()` here) in the same event loop, it leads to a deadlock.
Adding a `new_loop` parameter to the `run_sync` function allows to create a new event loop in the current Thread and allows to send a Message during a stream.
=> Avoid deadlock in event start

src/chainlit/cache.py, src/chainlit/config.py
LangChain cache can cause some issues (for instance with Streaming), so let's disable it by default.
The cache can now be enabled with the config param `cache = true`.
It can still be overridden with the CLI param `--no-cache`, which takes precedence.
=> Disable cache by default

src/chainlit/frontend/src/components/atoms/ClipboardCopy.tsx, src/chainlit/frontend/src/components/atoms/Collapse.tsx, src/chainlit/frontend/src/components/molecules/inputLabel.tsx, src/chainlit/frontend/src/components/organisms/chat/history/index.tsx, src/chainlit/frontend/src/components/organisms/chat/message/UploadButton.tsx, src/chainlit/frontend/src/components/organisms/inputs/selectInput.tsx
Context : 
MUI Imports increasing bundle size due to tree-shaking issues https://mui.com/material-ui/guides/minimizing-bundle-size
I tried with the babel plugins, none of them fixed the issue (https://mui.com/material-ui/guides/minimizing-bundle-size/#option-two-use-a-babel-plugin) and also found https://github.com/Dschungelabenteuer/vite-plugin-entry-shaking wich looks like only for internal package and not node modules. 
Explicit import icons decrease the bundle size on first load from 20mb to 13mb, so maybe if we do this for all MUI imports, it should be better! 
Open to recommandations, I did not found any plugins or config to fix this..
Edit: Maked vite plugin work following Tamagui config (https://github.com/tamagui/tamagui/blob/878ed1e591f9f29a56b0b9ba918eccf4b8d8d949/packages/cli/s …
=> refactor: Explicit import Icons

src/chainlit/frontend/src/components/organisms/chat/message/content.tsx, src/chainlit/message.py
=> add support for json objects in the Message component

src/chainlit/playground/providers/langchain.py
A previous commit made the langchain python package a requirement for chainlit to run correctly. Langchain is an optional dependency, so this commit fixes the bug by only requiring langchain classes from the langchain-related classes.
Also removed unused imports.
=> fix: get rid of the langchain requirement

backend/chainlit/config.py, frontend/setup-tests.ts, frontend/src/AppWrapper.tsx, frontend/src/components/atoms/Collapse.tsx, frontend/src/components/organisms/chat/message/content.spec.tsx, frontend/src/components/organisms/chat/message/content.tsx, frontend/src/components/organisms/chat/message/message.spec.tsx, frontend/src/components/organisms/chat/message/message.tsx, frontend/src/state/project.ts, frontend/src/state/settings.ts
- Add a `default_collapse_content` options in Chainlit configuration
- Update `Collapse` atom props to set default state
- Update `Content` organism with `preserveSize` props
- Update `Message` organism to decide `preserveSize` behavior
- Update vitest setup to clean up rendered element after testing 
- Added tests to `Message` organism
- with `e2e/streaming`
- reduce the sleep time
- increase the length of the message
- notice that the message  is no longer collapsed when reaching the limit
- with `e2e/cot`
- update the config with `UI.default_collapse_content = false`
- increase the response text length
- notice that the box is expanded by default
=> Add disable long message collapsing option

backend/chainlit/server.py, backend/chainlit/types.py
https://github.com/Chainlit/chainlit/assets/10745953/e03893e6-5a0f-442a-9640-0d21d06b41ee
- Add a new `GET /logo` endpoint accepting an optional `theme` path parameter.
- run chainlit
- go to `/logo`
- notice the default logo is displayed
- check with the parameter `?theme=dark`
- notice the default dark logo is displayed
- add a custom logo `logo_light` or `logo_dark` in the `public` folder
- run the `buildUi` script again
- repeat previous steps, notice that we display the custom ones
- remove every logos from `frontend/dist`
- notice that we raise an error
=> make logo configurable

libs/components/package.json, libs/components/src/auth/AuthLogin.tsx
https://github.com/Chainlit/chainlit/assets/10745953/3d1663be-1025-4cd2-9717-283236f7ea0f
- update `build:watch` script to improve dx
- oauth providers separator is only displayed when we receive at least a provider
- input validation error only appears when the field is touched (⚠️ not perfect yet, but I think we can postpone a more complete refactor, currently the UX is good enough)
- pressing enter will now send the signin form
- make sure to have no providers env keys
- notice that we no longer see the `OR` separator
- type a password, notice that the email is empty error is not displayed
- type an email, and empty the field, the error is properly displayed
- press `enter` to send the form, notice that it's being sent
=> Cloud Login UX fixes

libs/components/package.json, libs/components/src/auth/AuthLogin.tsx, libs/components/src/auth/AuthResetPassword.tsx
- Fix: generate type definition in dev mode 
- Flesh out the `AuthResetPassword` to properly use the cloud
- 💡 I took inspiration from the existing Auth0 forgot password form, for now I think the UI is servicable.
- ⚠️ explanation in the incoming cloud PR
=> Add forgot password UI

backend/chainlit/config.py, backend/chainlit/server.py, frontend/index.html
This pull request adds another parameter to the configuration file `config.toml`. It allows to add a custom CSS file so that you can customize the CSS of the UI. This CSS file will be then injected into the index.html of the frontend React project.
Here is how you inject the custom CSS file by editing `config.toml`:
```
[UI]
name = "Chatbot"
...
custom_css = '/assets/test.css'
```
=> Added mechanism to allow injecting custom CSS files for UI customization

libs/components/src/auth/AuthForgotPassword.tsx, libs/components/src/auth/AuthLogin.tsx, libs/components/src/auth/AuthResetPassword.tsx, libs/components/src/auth/index.tsx
- Rename existing `AuthResetPassword` Component into `AuthForgotPassword`
- Fix "link" in sign in form being of `type="submit"` sending the form
- Created `AuthResetPassword` the form to reset the password
- ⚠️ I haven't introduced the show password (because of confirmation password field, do you think it's necessary?)
- ⚠️ Explained in a separate PR
=> Add reset password page

backend/chainlit/input_widget.py, backend/pyproject.toml
Mypy 1.5.1 was complaining
```
chainlit/input_widget.py:17: error: Signature of "__post_init__" incompatible with supertype "dataclass"  [override]
chainlit/input_widget.py:17: note:      Superclass:
chainlit/input_widget.py:17: note:          def __post_init__(self: InputWidget) -> None
chainlit/input_widget.py:17: note:      Subclass:
chainlit/input_widget.py:17: note:          def __post_init__(self: InputWidget, tooltip: Any, description: Any) -> None
Found 1 error in 1 file (checked 48 source files)
 ELIFECYCLE  Command failed with exit code 1.
```
So i took a look at the input_widget file. To me there is a lot of dead code (plus the post_init was breaking mypy). Would love to have feedback on this to make sure I did not miss on something important.
Tested with prompt playground and …
=> update to mypy 1.5.1 and fix post_init liskov

libs/components/src/ActionList.tsx
If there is not enough actions to trigger the collapse and the window size is small, no actions are displayed
=> fix actions display on mobile

backend/chainlit/oauth_providers.py
Solving #425
- Add an env variable to toggle `single tenant` option (pick theses over decorator parameter because it would be a leak of abstraction)
- Add `OAUTH_AZURE_AD_ENABLE_SINGLE_TENANT=true`
- Update credentials for a single tenant application
- Notice that you can connect to chainlit app
=> Support Azure AD single tenant

backend/chainlit/element.py, backend/chainlit/message.py
Before patch:
https://github.com/Chainlit/chainlit/assets/10745953/c235c382-3fbb-47db-8e04-fa51d0466d67
After patch:
https://github.com/Chainlit/chainlit/assets/10745953/5036c8c3-6c3b-48c6-9c88-2be070d856ed
- In `message.py` parallelize message persistence
- In `element.py` parallelize element persistence
- Upload an element
- Notice that element can be uploaded and accessed
- Send a message
- Notice that persistence occurs after
=> Reduce perceived latency for users

backend/chainlit/__init__.py, backend/chainlit/message.py, backend/chainlit/types.py, cypress/e2e/action/main.py, cypress/e2e/action/spec.cy.ts, frontend/src/components/organisms/chat/inputBox/input.tsx, libs/components/src/messages/components/ActionButton.tsx, libs/components/src/types/file.ts
- Expand "ask user" capabilities by requesting users action:
- Update test to cover use case
- Build the ui
- Start `cypress/e2e/action/main.py`
- Notice the user being asked to take an action
=> Add ask user action

.eslintrc, cypress.config.ts, cypress/e2e/conversations/spec.cy.ts, frontend/src/components/organisms/chat/index.tsx, frontend/src/components/organisms/chat/inputBox/UploadButton.tsx, frontend/src/components/organisms/conversationsHistory/sidebar/OpenChatHistoryButton.tsx, frontend/src/components/organisms/conversationsHistory/sidebar/index.tsx, frontend/src/components/organisms/header.tsx, frontend/src/pages/Page.tsx, frontend/src/state/settings.ts, libs/components/hooks/useChat/state.ts
=> fix: Improve UX for mobile user

backend/chainlit/playground/providers/openai.py
Long time user, first time contributor. Apologies if I'm not following the right format for this PR.
When working with the Playground and AzureOpenAI, if you try to rerun your prompt for a new completion you receive the following error:
```
Error:
File "/.venv/lib/python3.11/site-packages/chainlit/playground/providers/openai.py", line 148, in create_event_stream
token = stream_resp.choices[0]["delta"].get("content", "")
~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
This is because when AzureOpenAI has "moderation" turned on, the first chunk has no 'choices' and instead just has "prompt_filter_results". It looks like this:
```
{
"id": "",
"object": "",
"created": 0,
"model": "",
"prompt_filter_results": [
{
"prompt_index": 0,
"content_filter_results": {
"hate": { …
```
=> Fix bug in playground for Azure OpenAI

backend/chainlit/socket.py, cypress/e2e/action/spec.cy.ts, cypress/e2e/avatar/spec.cy.ts, frontend/src/assets/chevronLeft.tsx, frontend/src/assets/chevronRight.tsx, frontend/src/assets/chevronUp.tsx, frontend/src/assets/user.tsx, frontend/src/components/atoms/buttons/userButton/avatar.tsx, frontend/src/components/organisms/chat/history/index.tsx, frontend/src/components/organisms/header.tsx, frontend/src/components/organisms/threadHistory/sidebar/TriggerButton.tsx, frontend/src/components/organisms/threadHistory/sidebar/index.tsx, libs/react-components/hooks/useColors.tsx, libs/react-components/src/Code.tsx, libs/react-components/src/elements/Avatar.tsx, libs/react-components/src/messages/Message.tsx, libs/react-components/src/messages/components/AskUploadButton.tsx, libs/react-components/src/messages/components/Author.tsx, libs/react-components/src/messages/components/DetailsButton.tsx, libs/react-components/src/messages/components/MessageTime.tsx
=> refactor: Design of messages

backend/chainlit/server.py
When setting the env var `CHAINLIT_COOKIE_SAMESITE=none` the `secure` parameter in the browser cookie needs to be set to `secure=True`. By default, `secure=False` so adding a boolean conditional and explicitly passing in the `secure` variable.
[Discord Discussion](https://discord.com/channels/1088038867602526210/1179183494124019852/1184663263070388244)
=> Set oauth cookie to secure=True when using same-site=none

backend/chainlit/secret.py
Some oauth providers will replace the `+` character with a <space> which fails the auth check.
Example:
1. Backend generates random string using `random_secret()` and saves it to a cookie. This value can contain a `+` character. Ex: `zu5ETd4U^JWX0Apd2VcP>j$ioE+/-aQr`
2. The state returned on the callback replaces the `+` with a <space>
3. When `oauth_callback()` compares the cookie value with the returned value it will fail as its comparing a `+` and a <space>.
This was encountered and reproduced several times with the Cognito IDP.
=> Remove `+` from secrets

libs/copilot/src/popover.tsx
- Add a zIndex property to the popover to prevent overlap from the target ui
=> Fix popover overlap

backend/chainlit/config.py, backend/chainlit/server.py
Adds a `custom_js` config option which will load the filename in the same manner as `custom_css`.
Tested on a personal project.
=> adds custom_js

backend/chainlit/__init__.py, backend/chainlit/openai/__init__.py, backend/chainlit/socket.py
- This simplifies instrumenting OpenAI calls
- Reuses the literalai OpenAI instrumentation
- Creates a new step for each OpenAI call, with the call details in the generation property
Depends on https://github.com/Chainlit/python-client/pull/43
=> Add OpenAI integration

backend/chainlit/llama_index/__init__.py, backend/chainlit/llama_index/callbacks.py, backend/pyproject.toml, cypress/e2e/llama_index_cb/main.py
Title: Fix: LlamaIndex 0.10.x migration
---
**Description:**
This pull request addresses the issue reported in [Chainlit #752](https://github.com/Chainlit/chainlit/issues/752) regarding migration problems encountered with LlamaIndex version 0.10.x. The main focus of this fix is to ensure compatibility and smooth migration from earlier versions to LlamaIndex 0.10.x without causing disruptions to existing functionalities.
**Changes:**
- Fixed all breaking changes that resulted from deprecated methods and properties in the new version.
- Updated the llama_index test to work with this newer version.
=> Fix: LlamaIndex 0.10.x migration

backend/chainlit/config.py, backend/chainlit/server.py, cypress/e2e/custom_build/.chainlit/config.toml, cypress/e2e/custom_build/main.py, cypress/e2e/custom_build/public/.gitignore, cypress/e2e/custom_build/public/build/frontend/dist/index.html, cypress/e2e/custom_build/spec.cy.ts
This will allow developers to easily replace the frontend code with their own built versions, thereby more flexibly customizing the UI.
=> Add custom frontend build

backend/chainlit/config.py, cypress/e2e/ask_multiple_files/.chainlit/config.toml, cypress/e2e/chat_profiles/.chainlit/config.toml, cypress/e2e/copilot/.chainlit/config.toml, cypress/e2e/custom_build/.chainlit/config.toml, cypress/e2e/elements/.chainlit/config.toml, cypress/e2e/llama_index_cb/.chainlit/config.toml, cypress/e2e/plotly/.chainlit/config.toml, cypress/e2e/tasklist/.chainlit/config.toml, cypress/e2e/upload_attachments/.chainlit/config.toml, frontend/src/components/organisms/chat/index.tsx, frontend/src/components/organisms/chat/inputBox/UploadButton.tsx, frontend/src/state/project.ts, libs/copilot/src/chat/body.tsx, libs/react-components/hooks/useUpload.tsx
We've implemented support for restricting multi modal inputs by mime type, file size and number of files, similar to AskFileMessage, giving developers a bit more flexibility in choosing what inputs to allow for the application.
This will not return any error, but will restrict the user from uploading files that don't match the specifications.
=> Multi-modal support for file size, mime types and number of files

backend/chainlit/langchain/callbacks.py
**Issue**
Running this code:
```
@cl.on_message
async def main(message: cl.Message) -> cl.Message:
cb = cl.AsyncLangchainCallbackHandler(
stream_final_answer=True,
answer_prefix_tokens=["FINAL", "ANSWER"],
)
cb.answer_reached = True
chain = cl.user_session.get("chain")
await chain.ainvoke(
message.content,
cast(RunnableConfig, {"callbacks": [cb]}),
return_only_outputs=False,
include_run_info=False,
)
```
you get an UnboundLocalError while updading the final stream:
`Errror in LangchainTracer.on_llm_end callback: local variable 'completion' referenced before assignment")`
This happens because a branch of the `if` (at line 502) does not initiate the `completion` variable, and it fails at line 562 since `completion` is not defined.
**Fix**
Define `completion` as needed.
=> Fix 'completion' referenced before assignment in LangchainTracer

backend/chainlit/server.py
Services like uptime-robot use a HEAD request to do status checks; this discards the response body and returns only headers. I've added a head route on top of '/' that returns properly. Right now uvicorn returns a 405 method not allowed
This doesn't interfere with the GET wildcard route, but we can easily move this over to a /status route if so desired.
=> feat: add HEAD route for '/' to support status checks

backend/chainlit/config.py
Closes #790 .
The issue was present when the venv was created in the same dir as the project using chainlit. On reload the code that was supposed to clear the modules related to the app from `sys.modules` also cleared chainlit itself which led to a reload and a new config object being initialized when `config.py` module was loaded. The `socket.py` module still had the reference to the old config module though, which resulted in reload failing. The lesson here is - module reloading in python is HARD and should really not be attempted. ;)
The fix checks where the modules are installed (venv or regular installation) and prevents their reload. This fixes all cases EXCEPT the `hello.py` in the chainlit repo - as the chainlit code is in the same dir as the demo file it's imporsible to say …
=> Do not reload installed packages on file change

backend/chainlit/data/__init__.py
There is argument type inconsistency between BaseDataLayer.create_element and ChainlitDataLayer.create_element.
I checked the type running on my local environment and confirmed that it is Element type.
=> fix BaseDataLayer create_element type

backend/chainlit/cli/__init__.py, backend/chainlit/config.py, backend/chainlit/server.py, backend/chainlit/translations.py, backend/chainlit/translations/en-US.json, frontend/src/AppWrapper.tsx, frontend/src/components/i18n/Translator.tsx, frontend/src/components/molecules/auth/AuthForgotPassword.tsx, frontend/src/components/molecules/auth/AuthLogin.tsx, frontend/src/components/molecules/auth/AuthResetPassword.tsx, frontend/src/components/molecules/auth/AuthTemplate.tsx, frontend/src/components/molecules/auth/AuthVerifyEmail.tsx, frontend/src/components/molecules/auth/ProviderButton.tsx, frontend/src/components/molecules/messages/components/DetailsButton.tsx, frontend/src/components/organisms/chat/Messages/index.tsx, frontend/src/components/organisms/chat/index.tsx, frontend/src/components/organisms/chat/inputBox/input.tsx, frontend/src/components/organisms/header.tsx, frontend/src/components/organisms/threadHistory/sidebar/TriggerButton.tsx, frontend/src/components/organisms/threadHistory/sidebar/filters/FeedbackSelect.tsx, frontend/src/components/organisms/threadHistory/sidebar/filters/SearchBar.tsx, frontend/src/hooks/useLLMProviders.ts, frontend/src/pages/Env.tsx, frontend/src/pages/Login.tsx, frontend/tests/message.spec.tsx, libs/copilot/src/app.tsx, libs/copilot/src/components/Input.tsx
- add a translation linter
- add translation file fallback
- move translations api from settings to its own route
- add fastapi gzip middleware
- enable a fallback (skeleton component) in the existing Translator component
- add a new hook to return a string (with a `...` fallback)
- switch to using the Translator as much as possible (to benefit from the skeleton fallback)
- if the Translator can't be used, use the new `useTranslation` hook instead of the one from `react-i18next` (to benefit from the fallback which avoids displaying the translation keys)
Example of a simulated long translation loading time:
- If a key is missing from your translation file, it won't load in the UI, this is why you should use the translation linter to check your local translation files.
- The translation …
=> Improve translations

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
- prevents all untriaged issues from going on the community board
=> chore: label new issues as "needs-triage"

frontend/src/components/atoms/elements/Text.tsx
This fixes #597 and #862 
Text elements can now use html to render content vs just messages.
=> Allow html in text elements

backend/chainlit/types.py, frontend/src/App.tsx, frontend/src/state/project.ts
This change allows for setting a `default` ChatProfile.
This can be used to preselect a user's last used ChatProfile when they start a new chat.
```python
@cl.set_chat_profiles
async def chat_profile(current_user: cl.User):
last_used_profile = await user_cache.get(current_user.identifier, "last_used_profile")
profiles = [
cl.ChatProfile(
name="GPT-3.5",
markdown_description="The underlying LLM model is **GPT-3.5**.",
icon="https://picsum.photos/200",
),
cl.ChatProfile(
name="GPT-4",
markdown_description="The underlying LLM model is **GPT-4**.",
icon="https://picsum.photos/250",
),
]
default_profile = next((p for p in profiles if p.name == last_used_profile), None)
if default_profile:
default_profile.default = True
return profiles
=> Allow for setting a `ChatProfile` default

CHANGELOG.md, backend/chainlit/emitter.py, backend/chainlit/socket.py, cypress/e2e/data_layer/main.py, cypress/e2e/data_layer/spec.cy.ts, frontend/src/components/molecules/chatProfiles.tsx, frontend/src/components/organisms/chat/index.tsx, frontend/src/components/organisms/threadHistory/Thread.tsx, frontend/src/components/organisms/threadHistory/sidebar/ThreadList.tsx, frontend/src/components/organisms/threadHistory/sidebar/index.tsx, frontend/src/pages/ResumeButton.tsx, frontend/src/pages/Thread.tsx, libs/react-client/src/state.ts, libs/react-client/src/useChatInteract.ts, libs/react-client/src/useChatMessages.ts, libs/react-client/src/useChatSession.ts
- re-fetch the thread list on first interaction
- navigate to /thread/:id url when creating a new conversation
- update the /thread/:id page to allow for displaying the current chat
- add `threadId` to `useChatMessages` to get the current conversation thread id
- update "back to conversation" links
- clear current conversation when deleting the current thread
based on the work from @BrittleFoot in https://github.com/Chainlit/chainlit/pull/838
=> Update thread list on first interaction

frontend/src/components/organisms/chat/inputBox/input.tsx
fixes #743
- only consider paste input if it can't be converted as text
=> fix: pasting from microsoft products generates text instead of an image

backend/chainlit/input_widget.py
Allow for multiline `TextInput`
```python
@cl.on_chat_start
async def on_chat_start():
await cl.ChatSettings(
[
TextInput(
id="AgentName",
label="Agent Name",
initial="AI",
multiline=True
)
]
).send()
```
=> multiline text input

frontend/src/pages/Thread.tsx
Ensures returning to a previously created chat will display all the messages.
=> do not prevent thread revalidation

frontend/src/components/atoms/inputs/selects/MenuItem.tsx
This ensures menu items display the item label rather than value.
**ex:**
```python
@cl.on_chat_start
async def on_chat_start():
await cl.ChatSettings(
[
Select(
id="Model",
label="OpenAI - Model",
items={
"GPT-3.5-Turbo": "gpt-3.5-turbo",
"GPT-4": "gpt-4-turbo"
},
initial_value="gpt-4-turbo",
)
]
).send()
```
**bug:** the value is displayed instead of the label for each menu option
**fix:**
=> use the label for menu item

backend/chainlit/socket.py
Execute the on_chat_resume decorator before the resume_thread emitter. This allows the `thread` in on_chat_resume to be updated on load.
Use case: When using Elements with time-limited signed links, regenerate the signed links and update the Elements when resuming a chat.
=> Fix: Run code.on_chat_resume() before emitter.resume_thread()

backend/chainlit/discord/app.py, backend/chainlit/slack/app.py, backend/chainlit/types.py, frontend/src/components/molecules/messages/components/FeedbackButtons.tsx, libs/react-client/src/types/feedback.ts
Added threadId to Feedback. This will allow for getting the associated threadId easily. Plan to use this in adding document database data layers to chainlit like Dynamo. Discussed with @willydouhard
=> Added threadId to Feedback

backend/chainlit/config.py, frontend/src/App.tsx
Enable option to change primary/secondary font colors for light/dark mode. Useful when using non-standard background colors.
@tpatel @willydouhard Need your guidance here as I'm not a frontend expert and permission issues prevent me from fully testing.
```toml
[UI.theme.light.text]
#primary = "#212121"
#secondary = "#616161"
[UI.theme.dark.text]
#primary = "#EEEEEE"
#secondary = "#BDBDBD"
```
Resolves #673 
Example before this PR aims to solve. when setting light mode with the below options:
Settings:
```toml
[UI.theme.light]
background = "#17234E"
paper = "#1F397F"
[UI.theme.light.primary]
main = "#f5f5f5"
dark = "#00CED1"
light = "#D3D3D3"
```
=> Add font colors to config.toml 

backend/chainlit/data/__init__.py, backend/chainlit/data/sql_alchemy.py, backend/chainlit/element.py, cypress/e2e/data_layer/main.py
Adding this as prep for a custom data layer. This change will allow more flexible custom data layers, especially document ones like Dynamo.
Currently you can get the threadId in create element:
```python
async def create_element(self, element: "Element"):
thread_id = element.thread_id)
```
This change adds the thread_id param to delete element:
```python
async def delete_element(self, element_id: str, thread_id: Optional[str]):
```
All current data layers have been modified to accept the new param. The [Custom Data Layer API Docs](https://docs.chainlit.io/api-reference/data-persistence/custom-data-layer) will need to be updated. Should not be a breaking change but should be a mention in a migration guide.
=> Added threadId to Element

backend/chainlit/translations/en-US.json
fix small typo (occured->occurred)
=> fix en-US.json small typo

backend/chainlit/data/sql_alchemy.py
Fixed bug in sql_alchemy.py:delete_step: Wrong/non-existing primary key name for steps_query (was "forId" instead of "id", "forId" does not exist in table "steps") - probably a copy/paste bug from the previous line of code.
=> Update sql_alchemy.py - bugfix for delete_step

backend/chainlit/server.py
The callback path for authentication in Azure AD, and possibly others, was unintentionally broken in 8ecd415 by modifying the user-facing path.
This commit reverts one line of that change to restore it to its previous state.
=> fix: Azure authentication

backend/chainlit/langchain/callbacks.py
- added `process_content` to get content according to language
- applied it to `input` / `output` / `variables`
- run the cookbook https://github.com/Chainlit/cookbook/tree/main/langchain-ask-human 
Use the version from [this PR](https://github.com/Chainlit/cookbook/pull/129) because it fixes an LC import.
Had to remove process content on `output` because of error:
```
2024-07-04 10:01:24 - An output parsing error occurred. In order to pass this error back to the agent and have it try again, pass `handle_parsing_errors=True` to the AgentExecutor. This is the error: Could not parse LLM output: Question: I need to order pizza for a hackathon. How many should I order?
Thought: To determine how many pizzas to order, I need to know the number of people attending the hackathon and the average …
```
=> fix: langchain integration input/output format

frontend/src/App.tsx
The ability to inject custom CSS into the frontend is very useful but there is no way to differentiate between light and dark modes within the CSS.
This simply adds a class that changes based on the selected theme so custom css can be applied to only light or dark mode.
=> add css class based on active theme

backend/chainlit/config.py
Fixes #1204.
Also adds a comment for the setting:
> \# Allow users to edit their own messages
=> fix: edit_message in correct place in config.toml

backend/chainlit/data/__init__.py
Fixes #1232
Modify Chainlit so that HTTP errors which occur while sending steps to LiteralAI are caught and logged.
Prior to this change, HTTP errors such as timeouts result in a series of cascading exceptions and tracebacks that begin with "Task exception was never retrieved" and continue for several traceback iterations. The result is a very verbose log which is hard to understand and debug.
After this change we will see one-line error messages in the log when HTTP errors occur, rather than a series of tracebacks.
In the future we might want to improve this further by retrying (sending the steps again) when the HTTP error is temporary.
=> Gracefully handle HTTP errors when sending steps

CHANGELOG.md, backend/chainlit/config.py
Adding `CHAINLIT_APP_ROOT` ENV Variable to modify `APP_ROOT`
* This is vital. When deploying, it can rely on a centralised config files. 
* Very Minor Change
* Only one line change 
* Replacing `APP_ROOT = os.getcwd()` with `APP_ROOT = os.getenv("CHAINLIT_APP_ROOT", os.getcwd())`
=> Adding CHAINLIT_APP_ROOT to modify APP_ROOT

.github/actions/poetry-python-install/action.yaml, .github/workflows/e2e-tests.yaml, .github/workflows/mypy.yaml, .github/workflows/pytest.yaml
* Run unittest on all supported Python versions, to provide stronger support guarantees.
* Local GH action Python/Poetry (dependency) install with caching.
Faster test runs, more consistency, less duplication. 
Saving test minutes and being gets important once we start doing things like testing multiple FastAPI versions.
=> Various improvements in tests/CI

.github/workflows/publish.yaml
Fixup publish workflow; tests has been renamed to e2e-tests.
We're gonna ensure the entire CI passes instead.
=> Fix publish workflow.

.github/workflows/ci.yaml, .github/workflows/publish.yaml
* Allow calling ci workflow from publish.
* Use DRY poetry/python action everywhere.
=> Fix publishworkflow again

backend/chainlit/data/sql_alchemy.py
The [step attribute show_input](https://github.com/Chainlit/chainlit/blob/main/backend/chainlit/step.py#L62) can be None, True/False, or the markdown syntax language. The code currently only handles `bool` not `str` so when resuming chats input is not displayed.
```py
showInput: Optional[Union[bool, str]]
```
I switched the if/then to only return None when it's None or "false" (data layer makes this a string)
=> BUGFIX | SQLAlchemy - Fix show_input on chat resume

backend/chainlit/llama_index/callbacks.py, backend/tests/llama_index/test_callbacks.py
In Llama Index, tool-calling events are emitted with the event type of `FUNCTION_CALL`. All tools in Llama Index, when used, emits these events, so they should definitely be supported in Chainlit.
**Example usage** is in [this repo](https://github.com/StarsRail/Cocai). This is a simple LLM agent that can roll a dice for you. The dice-rolling capability is implemented as simple `random.randint` call ([code](https://github.com/StarsRail/Cocai/blob/b94d26c38aae1542c8ceea316af3822aed2c3a0e/tools.py#L26)) wrapped with `FunctionTool` ([code](https://github.com/StarsRail/Cocai/blob/b94d26c38aae1542c8ceea316af3822aed2c3a0e/main.py#L125-L127)).
| Before | After | 
| --- | --- |
|  <img width="773" alt="image" src="https://github.com/user-attachments/assets/1a1d214b-eda6-4297-ae8d-34a1850f2696"> …
=> [fix] `LlamaIndexCallbackHandler` to support displaying function calls as tools in CoTs

.github/actions/pnpm-node-install/action.yaml, .github/actions/poetry-python-install/action.yaml, .github/workflows/e2e-tests.yaml, .github/workflows/publish.yaml, frontend/package.json, libs/react-client/package.json
* Upgrade actions/cache to v4, solves Node 12 not supported warning. Resolves: 
"The following actions uses node12 which is deprecated and will be forced to run on node16: actions/cache@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/"
* Bump various action versions to latest major version.
* Bump Node for building to latest LTS (Node 16 has EOL'd a long time ago).
* DRY local action for node/pnpm builds similar to python/poetry action.
* Use `prepublishOnly` to avoid building internal deps during install (e.g. build only during publish or build).
=> Various improvements in GH actions

backend/chainlit/data/sql_alchemy.py
`SQLAlchemyDataLayer` (`get_all_user_threads` method) doesn't return feedback_id of already existing feedback, when resuming already existing chat. This results in duplicating feedback when you want to change already existing feedback. Proposed change should fix this issue.
=> Added missing feedback_id.

backend/chainlit/message.py
Just removing an extraneous key/value declaration set during the creation of a dictionary.
`createdAt` is set on line 79 and line 85
https://github.com/Chainlit/chainlit/blob/122369a64ebdc3d34f6f88cbe24ec612d209c20b/backend/chainlit/message.py#L74-L93
=> Removed redundant key/value pair from dictionary creator

cypress/e2e/chat_profiles/main.py, cypress/e2e/chat_profiles/spec.cy.ts, frontend/src/components/molecules/chatProfiles.tsx
This pull request resolves #1256, where users are unable to interact with chat profile descriptions, such as scrolling through long descriptions or clicking links within them. The modifications ensure that the description popover remains open and interactable when the mouse hovers over it, and closes appropriately when the mouse leaves the popover area or a selection is made.
All changes were done in `chatProfiles.tsx`.
The main change was modifying `popoverOpen` to manage the open/close state of the description popover instead of the previous implicit check using `Boolean(anchorEl)`. The rest of the changes support properly opening and closing the description popover throughout all interactions with the chat profile `SelectInput`.
These changes allow developers to include longer …
=> Resolve #1256 - Fix Interaction Issues with Chat Profile Description Popover

backend/poetry.lock, backend/pyproject.toml
As we're relying on dataclasses pretty much everywhere, and we don't nearly have enough unit test coverage, I would like to ask the community to assist in manual testing before we ship this in the latest release (in addition to contributions to increase unittest coverage).
As discussed [here](https://github.com/Chainlit/chainlit/pull/1267#issuecomment-2315006242), we prefer to be careful when upgrading dependencies and would prefer to do it one by one. Otherwise, if something goes wrong, it will be extremely challenging to figure out _where_ it went wrong. (#1267)
Depending on the amount of testing/feedback we can get in, we hope to ship this with the coming release. We're also actively working towards allowing (editable) installs straight from GIT so users won't be as dependent on our …
=> Bump dataclasses to latest version.

.github/workflows/pytest.yaml, backend/chainlit/_utils.py, backend/chainlit/config.py, backend/chainlit/markdown.py, backend/chainlit/server.py, backend/tests/conftest.py, backend/tests/test_callbacks.py, backend/tests/test_server.py, cypress/e2e/readme/spec.cy.ts
Validate path hierarchy and path parameters for:
* `get_avatar`
* `project_settings
* `project_translations`
Includes test coverage for all relevant methods.
=> Fastapi parameter validation

README.md, backend/chainlit/cli/__init__.py, backend/chainlit/data/dynamodb.py, backend/chainlit/element.py, backend/chainlit/session.py, backend/chainlit/socket.py, frontend/src/components/atoms/elements/Plotly.tsx
=> Small text fixes

backend/chainlit/auth.py, backend/chainlit/cli/__init__.py, backend/chainlit/haystack/callbacks.py, backend/chainlit/langchain/callbacks.py, backend/chainlit/mistralai/__init__.py, backend/chainlit/oauth_providers.py, backend/chainlit/session.py, backend/chainlit/socket.py, cypress/e2e/action/main.py, cypress/e2e/chat_settings/main.py, cypress/e2e/data_layer/main.py, cypress/e2e/elements/main.py, cypress/e2e/llama_index_cb/main.py, cypress/e2e/plotly/main.py, cypress/e2e/pyplot/main.py, cypress/e2e/readme/main.py
First go-around of Python fixes with the [Trunk](https://trunk.io/) linters. I'm trying to keep the PR's small to make them easier to review. The commits are in decreasing order of priority in my opinion. There are a some more linter issues remaining which I intend to submit an additional PR for.
Please let me know of any problems with these commits. Some changes may be opinionated.
=> Python fixes

backend/chainlit/data/__init__.py
This avoids import loops and is a stepping stone towards pluggable data layers.
=> Don't run code on importing data module

backend/chainlit/oauth_providers.py, frontend/src/components/molecules/auth/AuthLogin.tsx
Fix the automatic enter of the only oauth providers, which makes it unable to logout
=> Fix auto login

CHANGELOG.md, backend/pyproject.toml
* Changelog for #1401 so contributors and users know what the bleep is going on.
* Bump version to 2.0.dev0 in keeping with semver, as pre-existing audio functionality is breaking.
=> Changelog for realtime

backend/chainlit/server.py, backend/tests/test_server.py
=> Update server.py to accept local languages such as es-419

backend/chainlit/data/base.py, backend/chainlit/data/dynamodb.py, backend/chainlit/data/sql_alchemy.py, backend/chainlit/data/storage_clients/azure.py, backend/chainlit/data/storage_clients/base.py, backend/chainlit/data/storage_clients/s3.py, backend/poetry.lock, backend/pyproject.toml, backend/tests/data/conftest.py, backend/tests/data/storage_clients/test_s3.py, backend/tests/data/test_sql_alchemy.py, cypress/e2e/custom_data_layer/sql_alchemy.py
PR to handle issue #1355 
I have added also a pytest for S3StorageClient and moto to mock aws connection. I am not so experienced with Azure so I did not add a test on it.
=> solving issue #1355 - Mixed dependencies in the Storage Clients module for the Data Layer 

backend/chainlit/server.py, backend/tests/conftest.py, backend/tests/test_server.py
Fixes https://github.com/Chainlit/chainlit/issues/1101 and includes and closes #1438.
=> Test and resolve issue with get_file and upload_file

backend/chainlit/oauth_providers.py
Use `OAUTH_<PROVIDER>_PROMPT` or `OAUTH_PROMPT` to override behaviour.
E.g. `OAUTH_PROMPT=login` to always require login, allowing for re-login after logout, even when only a single oauth provider is configured, without breaking prior user expecations.
Supersedes #1419 and #1362, requires documentation. 
Would be great to get this into 1.3.0 as shipping as-is would break some SSO users and require release of `1.4.0` (e.g. another breaking change) to fix it.
=> OAuth prompt configurable through environment

backend/chainlit/server.py
The `project/file/{file_id}` endpoint always returns 401 HTTP error. This prevent any Element from being displayed. Fixes https://github.com/Chainlit/chainlit/issues/1472
> [!IMPORTANT]  
> Users should not upgrade to versions 1.3.0 or 2.0.dev1
This comments out the problematic code and adds TODOs. This reopens #1101 and #1438 .
=> HOT FIX - Fixes Elements by reverting bug in #1441

backend/pyproject.toml
There was a prepending space in the license string...
=> Remove space in license string.

frontend/src/components/atoms/elements/InlinedDataframeList.tsx
Changes Dataframe width to fit-content instead of hardcoded 650px to better handle different sized dataframes and fill out the UI.
Before:
After:
Builds on #1373 . Awesome job getting this going @desertproject ! Streamlit's implementation is envious (export to csv, copy/paste, full screen, etc.) but after digging into their code it looks completely manual and complex! It's a bit suprising there's not a library for displaying Pandas dataframes out there with these features!
=> Auto-fit cl.Dataframe() to content

libs/react-client/src/types/file.ts, libs/react-client/src/useChatInteract.ts, libs/react-client/src/useChatSession.ts
AskUserMessage answer was added in frontend message memory without parentId resulting in wrongly ordered messages.
Detail in #1230
=> fix #1230 Incorrect message ordering in UI

cypress/e2e/chat_profiles/spec.cy.ts
This fixes a potential failure in the second chat_profiles test as it is not currently waiting after changing the model to GPT-4.
This test was constantly failing for me on the latest main without the added wait.
=> Add missing wait in chat_profiles test

lint-staged.config.js
The new commit hooks were assuming we were inside a poetry venv. This PR fixes that.
=> Allow running commit hooks outside of poetry/venv.

backend/chainlit/__init__.py, backend/chainlit/callbacks.py, backend/chainlit/config.py, backend/chainlit/data/__init__.py, backend/tests/conftest.py, backend/tests/data/test_get_data_layer.py, backend/tests/test_callbacks.py, backend/tests/test_server.py, cypress/e2e/custom_data_layer/sql_alchemy.py, cypress/e2e/data_layer/main.py, cypress/e2e/data_layer/spec.cy.ts
`@cl.datalayer` decorator for configuring data layers, rather than forcing users to override `_data_layer`.
This is a first step towards full support of pluggable data layers.
=> @data_layer API hook to configure data layer.

backend/chainlit/langchain/callbacks.py
1. Remove use_sync method in Langchain integration
2. Support Pydantic outputs with Langchain/Langgraph
=> feat: use async lc tracer instead of run_sync

libs/react-client/README.md, libs/react-client/src/useChatSession.ts
Reverts Chainlit/chainlit#1379
This is not working as intended. There are some race condition between events that we are subcribing to. So just revert and then we can implement a proper PR with tests.
=> Revert "feat: chainlit option to require websocket"

backend/chainlit/server.py, backend/tests/test_server.py
https://github.com/Chainlit/chainlit/issues/1458
=> fix(file_upload): validate mimetype as configured

backend/chainlit/action.py, backend/chainlit/chat_settings.py, backend/chainlit/config.py, backend/chainlit/element.py, backend/chainlit/input_widget.py, backend/chainlit/user.py
`Field` just so happens to be imported internally by the `pydantic.dataclasses` module, but this can change at any time.
=> Import `Field` from `pydantic` instead of `pydantic.dataclasses`

backend/chainlit/config.py, backend/chainlit/server.py, backend/chainlit/socket.py, cypress/e2e/copilot/.chainlit/config.toml, frontend/src/App.tsx, libs/copilot/src/chat/index.tsx, libs/react-client/src/useChatSession.ts
Fixing https://github.com/Chainlit/chainlit/issues/1279 and closes #1359 as well. Tested it on GCP with session affinity + 2 instances with this docker file
```dockerfile
FROM python:3.11-slim
RUN apt-get update && apt-get install -y \
git \
nodejs \
npm \
&& rm -rf /var/lib/apt/lists/*
RUN npm install -g pnpm
WORKDIR /app
COPY app.py .
RUN pip install --no-cache-dir git+https://github.com/Chainlit/chainlit.git@willy/sticky-sessions#subdirectory=backend/
ENV PORT=8000
ENV HOST=0.0.0.0
EXPOSE 8000
CMD ["chainlit", "run", "app.py", "--host", "0.0.0.0", "--port", "8000", "-h"]
```
=> fix: pass headers when connecting sockets

frontend/src/components/chat/WelcomeScreen.tsx
This pull request includes changes to the `WelcomeScreen` component to add support for allowing HTML and LaTeX in markdown descriptions. This code was copied from [ChatProfiles.tsx](https://github.com/Chainlit/chainlit/blob/main/frontend/src/components/header/ChatProfiles.tsx) where it's used for the over/popover.
Enhancements to markdown rendering:
* [`frontend/src/components/chat/WelcomeScreen.tsx`](diffhunk://#diff-16a9d38c0b482fad7d0a31014364eba7dfe107d5ec300041961a83ff1df8b07dR34-R36): Introduced new configuration options `allowHtml` and `latex` to control the rendering of HTML and LaTeX in markdown descriptions.
* [`frontend/src/components/chat/WelcomeScreen.tsx`](diffhunk://#diff-16a9d38c0b482fad7d0a31014364eba7dfe107d5ec300041961a83ff1df8b07dL55-R60): Updated the `Markdown` …
=> feat: Allow HTML for markdown_description in Welcome Screen

frontend/src/hooks/useFetch.tsx
Fixing https://github.com/Chainlit/chainlit/issues/1669
=> fix: only use credentials include for chainlit requestsC

.github/workflows/lint-backend.yaml, CHANGELOG.md, backend/chainlit/auth/cookie.py, backend/chainlit/data/chainlit_data_layer.py, backend/chainlit/message.py, backend/chainlit/server.py, backend/poetry.lock, backend/pyproject.toml, backend/tests/test_server.py
Fixing https://github.com/Chainlit/chainlit/issues/1658
=> fix: allow AskFileMessage even if spontaneous uploads are disabled

backend/chainlit/session.py, backend/chainlit/socket.py, backend/chainlit/user_session.py, backend/tests/conftest.py, backend/tests/test_user_session.py
This is a partial solution to this issue. https://github.com/Chainlit/chainlit/issues/1213
Adding access to `http_cookie` to `WebSocketSession` and `UserSession` facilitates the use of chainlit in enterprise applications that deploy multiple services under the same domain.
This pull request introduces support for handling HTTP cookies in the `backend/chainlit` module. The changes primarily involve adding a new `http_cookie` parameter to various methods and ensuring that this parameter is properly propagated throughout the session handling and testing code.
* [`backend/chainlit/session.py`](diffhunk://#diff-fbe9680de98b84f5b8bfb9643a3f9039c29e438592f42305e4acc9f6caaef2b2R67-R68): Added `http_cookie` parameter to the `__init__` method of several classes to handle HTTP cookies. …
=> feat: add http_cookie to WebsocketSession and UserSession

CHANGELOG.md, backend/chainlit/data/chainlit_data_layer.py, backend/chainlit/data/sql_alchemy.py, backend/chainlit/data/storage_clients/azure_blob.py, backend/chainlit/data/storage_clients/base.py, backend/chainlit/data/storage_clients/gcs.py, backend/chainlit/data/storage_clients/s3.py
To test:
Fixes for:
- https://github.com/Chainlit/chainlit/issues/1546
- https://github.com/Chainlit/chainlit/issues/1649
- deleting a thread removes objects on cloud storage for official + SQLAlchemy data layers (GCS/Azure/S3)
- store `props` as JSON in SQLAlchemy data layer
- cleanup + async wrappers for S3
- for both official & SQLAlchemy data layers
- connect to GCS/Azure/S3 storage
- start thread with image attachment -> get element URL from cloud storage
- delete thread
- check on cloud storage that object isn't there anymoer
- specific to SQLAlchemy data layer:
- start thread with custom element & check `props` properly written to DB
=> fix: data layers

backend/chainlit/config.py
Add detailed examples and guidelines for file upload MIME types configuration:
- Add examples for specific file types configuration
- Add examples for wildcard file type patterns
- Add examples for file extension mapping
- Add warning about using "*/*" pattern
- Set more practical default values
This helps developers better understand how to configure file upload types and avoid browser warnings about invalid MIME types.
=> docs: improve MIME types configuration guide

frontend/src/components/ChatSettings/index.tsx, frontend/src/components/CopyButton.tsx
Fixing https://github.com/Chainlit/chainlit/issues/1712 and https://github.com/Chainlit/chainlit/issues/1713
=> fix: only make the body of chat settings modal scroll

backend/chainlit/data/chainlit_data_layer.py
Countedragon reported [this issue](https://discord.com/channels/1088038867602526210/1329247912093286400/1329247912093286400) where boolean values for `showInput` make step ingestion on official data layer fail. 
Corresponding column on `Step` is TEXT in `schema.prisma` of `chainlit-datalayer`. Therefore, string cast is required prior to insert.
=> fix: store show input as string

backend/chainlit/data/chainlit_data_layer.py
Fix for bug reported in [this issue](https://github.com/Chainlit/chainlit-datalayer/issues/4#issue-2791603282). 
No need to limit var length on Prisma schema itself. 
To test, start a thread with a text exceeding 255 characters, make sure you don't get the error below and you can still search through your threads efficiently. 
Error that should not appear anymore:
```
2025-01-17 13:11:19 - Database error: index row requires 204672 bytes, maximum size is 8191
2025-01-17 13:11:19 - Error updating thread: index row requires 204672 bytes, maximum size is 8191
```
=> fix: limit thread name

backend/chainlit/translations/en-US.json, cypress/e2e/data_layer/spec.cy.ts, frontend/src/components/LeftSidebar/ThreadList.tsx, frontend/src/components/chat/Messages/Message/AskFileButton.tsx, frontend/src/components/header/NewChat.tsx
This PR adds internationalization support for several chat-related components:
- Related issue:
- #1710
- #1681
- #1640
- #1551
- #1550  
- Added translation paths in NewChat.tsx
- Updated corresponding strings in en-US.json under newChatDialog
- Added translation paths for renaming dialog and deletion dialog strings in ThreadList.tsx
- Added translation paths for time group labels (Today, Yesterday, etc.)
- Updated corresponding strings in en-US.json under threadList section
- Fixed e2e test selector to work with translated dialog buttons
- Changed button selector to use [role='alertdialog'] button.bg-primary instead of text content
- Added translation paths in AskFileButton.tsx
- Updated corresponding strings in en-US.json under askFileButton section
- All translations follow existing …
=> Add i18n Support for Chat Components

backend/chainlit/translations/bn.json, backend/chainlit/translations/en-US.json, backend/chainlit/translations/gu.json, backend/chainlit/translations/he-IL.json, backend/chainlit/translations/hi.json, backend/chainlit/translations/ja.json, backend/chainlit/translations/kn.json, backend/chainlit/translations/ml.json, backend/chainlit/translations/mr.json, backend/chainlit/translations/nl-NL.json, backend/chainlit/translations/ta.json, backend/chainlit/translations/te.json, backend/chainlit/translations/zh-CN.json, frontend/src/components/LeftSidebar/ThreadOptions.tsx
Added missing translations for the thread history menu dropdown options across all supported languages.
- Added new translation entries for thread menu options in all language JSON files
- Updated `ThreadOptions` component to use `Translator` with path `threadHistory.thread.menu.*`
=> feat(i18n): Add translations for thread menu options

cypress.config.ts
Intended to increase test robustness on Windows.
=> Increase Cypress E2E test timeout

frontend/src/components/chat/Messages/Message/AskActionButtons.tsx
Closes https://github.com/Chainlit/chainlit/issues/1688
**Before**
**After**
=> Wrap text content of AskActionButton

backend/chainlit/data/chainlit_data_layer.py, backend/chainlit/element.py
@yves03 reported https://github.com/Chainlit/chainlit/issues/1792
- override `props` in `create_element` with on conflict strategy
- remove persisted condition on deletion -> need to check why `self.persisted` is false upon element removal :/
- set up data layer with https://github.com/Chainlit/chainlit-datalayer/
- use the counter example from https://docs.chainlit.io/api-reference/elements/custom linked to above data layer
- validate that counter increments do show on `props` (count key incremented in DB)
- validate that clicking "Remove" deletes the `Element` record from DB
- add the `callAction` as described in issue above and validate the print works (no errors)
=> fix: add conflict strategy to create_element

libs/copilot/src/appWrapper.tsx, libs/copilot/src/types.ts, libs/copilot/src/widget.tsx
This pull request allows for customization of copilot styles and allows for customization of styles of the copilot container in expanded or collapse mode.
for example:
```js
window.mountChainlitWidget({
chainlitServer: url,
customCssUrl: '/public/copilot.css',
}
```
and copilot.css:
```css
#cl-shadow-root .copilot-container-expanded {
height: min(900px,calc(100vh - 150px));
}
#cl-shadow-root .copilot-container-collapsed {
width: min(600px,80vw);
}
```
other classes could be overwritten or customized as needed
=> feat: add support for custom CSS styles in copilot

backend/chainlit/server.py, backend/chainlit/utils.py
Fixing https://github.com/Chainlit/chainlit/issues/1819
=> fix: prevent chainlit sub app to default all endpoints

frontend/src/components/chat/MessageComposer/index.tsx, frontend/src/components/chat/Starter.tsx
Partial code of the feature introduced in https://github.com/Chainlit/chainlit/pull/1403 was removed after the recent UI refactoring.
This PR reintroduces the missing parts to allow including the current location/URL where the user is as part of the message metadata for further processing in `on_message(message: cl.Message)`
=> fix: reintroduce including URL location after UI refactor

frontend/src/components/chat/Messages/Message/index.tsx
Hello, the redesign of Chainlit on V2 introduced back an issue (https://github.com/Chainlit/chainlit/issues/1548) where the assistant messages would display "0" in some case when thread contains a AskActionMessage or AskFileMessage element.
This simply applies back the same fix as the PR https://github.com/Chainlit/chainlit/pull/1617 to change the logic on the frontend.
---
Before : 
After:
=> Fix: prevent showing 0's on resumed thread if AskAction/File was used

frontend/src/components/chat/MessageComposer/index.tsx
when I type something then delete to empty string in the input, the actual value is `\n`, so the button was not disabled.
=> fix: disable submit button when input is empty

frontend/tsconfig.json
Adding composite: true so that chainlit can built incrementally when referenced in another projects.
This is to support monorepo cloning chainlit and build . This should not be an issue with current chainlit project.
=> chore: allow chainlit to be built as dependencies

backend/chainlit/config.py, backend/chainlit/server.py
the github button in the UI wasn't really working, however this could now be achieved using `UI.header_links` from https://github.com/Chainlit/chainlit/pull/1836
=> chore: remove github config not used

backend/chainlit/config.py, frontend/src/components/ButtonLink.tsx, frontend/src/components/header/index.tsx, libs/react-client/src/types/config.ts
This PR allows to configure custom links to be added in the menu/navigation header by adding them in the config.toml file
For example:
```
[[UI.header_links]]
name = "Confluence"
icon_url = "https://www.atlassian.com/favicon.ico"
url = "https://www.atlassian.com"
[[UI.header_links]]
name = "Issues"
icon_url = "https://mintlify.s3-us-west-1.amazonaws.com/chainlit-43/_generated/favicon/favicon.ico?v=3"
url = "https://github.com/Chainlit/chainlit/issues"
```
That will result in the following:
=> feat: support adding custom links on the nav header

frontend/src/pages/Page.tsx
When using the application, there are warnings in the browser console about ResizablePanel configuration:
```
[Warning] Panel ":[id]:" has an invalid configuration: default size should not be less than min size
``` 
The warning occurs because the defaultSize (50) is less than minSize (60) in the main ResizablePanel of `Page.tsx`.
- Modified `defaultSize` from `50` to `60` to match `minSize` in the main `ResizablePanel` of `Page.tsx`
- Verified the warning no longer appears in the browser console when:
- Opening the application
- Navigating between different chat threads
- Verified the layout and resizing functionality remain unchanged
=> fix: set defaultSize equal to minSize in ResizablePanel to avoid warning

frontend/src/components/LeftSidebar/ThreadList.tsx
Fix an issue where deleting an active conversation would sometimes leave an orphaned empty thread record in the database, and optimize the thread deletion process.
When deleting the currently selected conversation, there was a race condition between the frontend state cleanup and the backend deletion process. This could result in an empty thread record being created with the same ID as the deleted thread.
1. Open the application
2. Select a conversation from the history
3. Delete the selected conversation
4. Check database - an empty thread record might remain
Modified the thread deletion process in `ThreadList.tsx`:
1. Ensured frontend state cleanup (`clear()`) happens before the deletion API request to prevent orphaned records
2. Optimized the navigation flow by moving it after thread …
=> fix: prevent orphaned thread record when deleting active conversation

frontend/src/components/chat/Messages/Message/Buttons/FeedbackButtons.tsx, frontend/src/components/ui/dialog.tsx, frontend/src/components/ui/sheet.tsx
When running `poetry install --with tests --with mypy --with dev`, the build process fails with sourcemap errors in three React components. These errors occur during the Vite build process for both `@chainlit/copilot` and `@chainlit/app`:
- Related issue #1764 
```
vite v5.4.14 building for production...
Error when using sourcemap for reporting an error: Can't resolve original location of error.
``` 
The errors consistently appear in three files:
- `src/components/ui/dialog.tsx`
- `src/components/ui/sheet.tsx`
- `src/components/chat/Messages/Message/Buttons/FeedbackButtons.tsx`
The affected components include the `'use client'` directive, which is specific to Next.js and unnecessary in a Vite project. These components appear to be generated using shadcn/ui CLI tool, which defaults to …
=> fix: Remove unnecessary 'use client' directives to fix sourcemap errors

frontend/src/components/header/index.tsx
Fix React warning about missing key prop in ButtonLink components rendered in header.
- Added unique key prop to ButtonLink components in header/index.tsx
- Key is generated using combination of link name, URL and index to ensure uniqueness
=> fix: add key prop to ButtonLink components in header

backend/chainlit/data/sql_alchemy.py
Fixes an issue arising with `SQLAlchemyDataLayer` in which a custom element's state would not be properly reloaded after resuming a chat thread due to a null value for the element's `props`. https://github.com/Chainlit/chainlit/issues/1799 documents the issue in more detail, including a fix.
In `sql_alchemy.py`, the SQL query contained in `elements_query` is missing the `props`. Since this is missing, any reloaded custom element will have an empty value for `props` thereby ignoring its latest state.
Also, there was an error on insertion of new elements into the database in an identical fashion to https://github.com/Chainlit/chainlit/pull/1794 which fixes the same error in the default Postgres data layer. This PR includes the same fix for the SQLAlchemyDataLayer which also blocked a …
=> fix: Include element `props` in SQLAlchemyDataLayer query for elements

backend/chainlit/server.py
When we add specific file extensions in the spontaneous_file_upload.accept like this : 
```toml
[features.spontaneous_file_upload]
enabled = true
accept = { "application/octet-stream" = [".xyz", ".pdb", ".aac"] }
```
If the endpoint receive a file with an extension in upper case an error is reported. We have many os, some are case sensitive some not. In case sensitive os'es extensions like .MP3, .mp3, Mp3 or event mP3 is interpreted as the same extension.
This change allow those os'es to send files whatever the extension's case.
=> fix: file extensions are now checked in lowercase for uploads

backend/chainlit/element.py
Fixes #1831 
Element type "file" was being used for both `type` and `mime`
After changing mime to "mime" we get the intended results
=> fix: Fix Element mime type by fixing from_dict()

frontend/src/components/Markdown.tsx, frontend/src/components/MarkdownAlert.tsx
When `unsafe_allow_html = true`, markdown-alert component has two issues:
1. The ::: syntax fails to parse correctly
2. HTML alert tag is not supported at all
1. Fixed alert syntax parsing when `unsafe_allow_html = true`
2. Added HTML tag support for alerts
1. With `unsafe_allow_html = true`:
- Verify both ::: syntax and HTML tag syntax work
- Check all alert types render correctly
- Confirm styling and icons are consistent across both syntaxes
2. With `unsafe_allow_html = false`:
- Verify ::: syntax works as before
- Confirm HTML tags are escaped and shown as text
```python
await cl.Message(content="::: idea\nInnovative idea\n:::\n\n").send()
``` 
```html
<alert type="idea">Innovative idea</alert>
``` 
Add type validation in both markdown mode and html tag mode.
If type error, alert will …
=> fix: markdown alert syntax support with unsafe_allow_html = true

backend/chainlit/auth/cookie.py
This pull request fixes an issue where `clear_auth_cookie` did not explicitly specify the `secure` and `samesite` attributes when deleting authentication cookies.  
- The `set_auth_cookie` function correctly sets cookies using the `_cookie_secure` and `_cookie_samesite` values.  
- These values are derived from the environment variable `CHAINLIT_COOKIE_SAMESITE`.  
- If `CHAINLIT_COOKIE_SAMESITE` is `"none"`, then `_cookie_secure` is set to `True`, ensuring the cookie is only sent over HTTPS.  
- Otherwise, `_cookie_secure` is `False`.  
- However, `clear_auth_cookie` did not apply these settings when deleting cookies.  
- If a user had customized `CHAINLIT_COOKIE_SAMESITE` to a value other than the default (`"lax"`), the logout process could fail because the browser might not clear the …
=> Fix: Ensure clear_auth_cookie uses the correct secure and samesite settings

backend/chainlit/data/sql_alchemy.py
**Describe the bug**
In SQLAlchemy data layer, create_step is executed before update_thread which prevents first user message from being saved in the database with a threadId assigned resulting in cutting it out when on_chat_resume is triggered.
Here's what happened when I send the first message to the UI: 
An error occurred: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.ForeignKeyViolationError'>: insert or update on table "steps" violates foreign key constraint "steps_threadId_fkey"
DETAIL:  Key (threadId)=(7bfc3437-cf41-417f-8fbb-642fa25b420d) is not present in table "threads".
**How I fixed it**
I added this line of code at the beginning of 'create_step' function:
`await self.update_thread(step_dict["threadId"])`
forcing update_thread to be …
=> fix: threadId assignment to first user message

frontend/src/components/LeftSidebar/ThreadList.tsx
This PR fixes the inconsistent order of thread history groups in the left sidebar. The groups (Today, Yesterday, Previous 7 days, Previous 30 days) were stored as object keys, and JavaScript does not guarantee their order. I added explicit sorting using a fixed order array so that the groups always appear in the intended order.
=> fix: Sort thread history groups in fixed order

backend/chainlit/slack/app.py
**Thread ID Generation Inconsistency:** 
There are two different thread ID generation approaches in the handle_message function. The first one is immediately overwritten by the second:
```diff 
- thread_id = str(
-     uuid.uuid5(
-         uuid.NAMESPACE_DNS,
-         message["channel"] + datetime.today().strftime("%Y-%m-%d"),
-     )
- )
thread_ts = message.get("thread_ts", message["ts"])
thread_id = str(uuid.uuid5(uuid.NAMESPACE_DNS, thread_ts))
```
=> chore(slack): Remove redundant thread ID generation

libs/react-client/src/useChatSession.ts
When resuming thread, the backend has already sent the chat setting values to the frontend. However,
the frontend doesn't resume the values. As a result, the setting button will be disappeared after resuming
the thread.
This PR will resume the setting values in the frontend when resuming the thread to fix the problem.
=> fix(react-client): Chat settings won't be resumed when resuming thread

CHANGELOG.md, backend/chainlit/server.py
Fixing https://github.com/Chainlit/chainlit/issues/1986
=> fix: oauth redirection with root path = '/'

backend/chainlit/mcp.py, backend/chainlit/server.py
Some MCP servers need env vars to set API keys, configure, etc. This commit will add support to set env vars from command line.
=> feat(backend/mcp): Support set env vars from command line

frontend/src/components/header/ChatProfiles.tsx
Fix an issue where model description (in Chat Profiles) does not disappear when quickly hovered
=> fix: chat_profiles model description

frontend/src/components/LeftSidebar/ThreadList.tsx
When deleting a chat history session from the sidebar, a WebSocket error occurs:
"WebSocket is closed before the connection is established."
Added a short delay (300ms) after clearing the current session before proceeding with the delete operation. This gives the WebSocket enough time to properly reconnect before continuing with the session deletion process.
=> Fix: Resolve WebSocket connection error when deleting chat history

backend/chainlit/types.py, frontend/src/components/chat/MessageComposer/CommandButtons.tsx, frontend/src/components/chat/MessageComposer/Input.tsx, frontend/src/components/chat/MessageComposer/index.tsx, frontend/src/state/chat.ts, libs/react-client/src/types/command.ts
This pull request introduces a new feature to support persistent commands in the chat message composer. The most important changes include updates to the type definitions, state management, and UI components to handle persistent commands.
* [`backend/chainlit/types.py`](diffhunk://#diff-9feb39b471289c6ef43961ab57fa796d091c790be59c90f3351c4253fa66512dR285-R286): Added a `persistent` field to the `CommandDict` class to indicate whether a command should be persistent.
* [`libs/react-client/src/types/command.ts`](diffhunk://#diff-fc2455ffd977138fa703bd374602f0e1dd40c44a0f8ceee57b683b868bb31cfdR6): Added a `persistent` field to the `ICommand` interface to support the new persistent command feature.
* [`frontend/src/state/chat.ts`](diffhunk://#diff-821401cbf8f91acfc7c9aac12260f6b1d41ce3650b5d12e …
=> Add a new field to allow commands to be persistent between messages

backend/chainlit/socket.py
With SQLAlchemy on SQLite, the data type return is str not dict. Check if the metadata field type is string, then convert to dict by json.loads
```
File "/opt/miniconda3/lib/python3.12/asyncio/tasks.py", line 314, in __step_run_and_handle_result
result = coro.send(None)
^^^^^^^^^^^^^^^
File "/Users/kaija/Desktop/demo/venv/lib/python3.12/site-packages/socketio/async_server.py", line 612, in _handle_event_internal
r = await server._trigger_event(data[0], namespace, sid, *data[1:])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/kaija/Desktop/demo/venv/lib/python3.12/site-packages/socketio/async_server.py", line 640, in _trigger_event
ret = await handler(*args)
^^^^^^^^^^^^^^^^^^^^
File "/Users/kaija/Desktop/demo/venv/lib/python3.12/site-packages/chainlit/socket.p …
```
=> fix: backward compatible with sqlite+sqlalchemy

backend/chainlit/langchain/callbacks.py
Tags are not traced on LangChain Tracer due to this missing line. I added it so that they can also be traced.
=> Added tags tracing on LangChain tracer

backend/chainlit/config.py, backend/chainlit/mcp.py, backend/chainlit/server.py
Some mcp servers are implemented using compiled language (such as go), and can't run via `npx` or `uvx`. This PR supports to custom allow list for the commands to run mcp servers.
=> feat(mcp): Support custom cmd allow list for mcp server

backend/chainlit/data/storage_clients/azure_blob.py
fix https://github.com/Chainlit/chainlit/issues/1756
This PR updates the Azure Blob Storage implementation of `upload_file` to return a consistent response format that includes both `object_key` and `url` keys, aligning with other storage providers like S3 and GCS.
The current implementation returns:
```python
{
"path": object_key,
"size": properties.size,
}
```
While the S3 implementation returns:
```python
{
"object_key": object_key,
"url": url
}
```
Currently, when using `SQLAlchemyDataLayer` with Azure Blob Storage, uploaded images disappear after page reload. This is because:
1. The Element data model expects either a `url` or `chainlit_key` to display media
2. Frontend components check for `element.url` first when rendering elements
3. When saving to the database, …
=> Fix: Images disappear after page reload when using AzureBlobStorageClient

frontend/src/App.tsx, frontend/src/components/chat/Messages/index.tsx
This PR:
- Adds a loader that is used until authentication information is ready. This prevents flickering on app load when the initial UI (for an unauthenticated user) is displayed first and then replaced with the authenticated user's version.
- Removes the blinking cursor on the `on_chat_start` message loading (the large black dot below the chat input).
Before:
https://github.com/user-attachments/assets/f4cd157a-0620-400e-94d1-08703d328373
After:
https://github.com/user-attachments/assets/16108af1-5aa9-44b8-b304-8f54e151fce6
=> fix: flickering on app start

frontend/src/components/chat/MessageComposer/Attachment.tsx
Fixes #2031 and #1072 
The problem is that `react-file-icon` works by using the file extension to make the right icon (.txt, .xlsx, .pptx, etc.). This code was inferring the extension by taking what's after the `/` so mimes like application/txt becomes `txt` and application/pdf becomes `pdf`. This works fine. The problem is that for Microsoft Office files in particular (although there are others) the mimes are these:
```
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet #Excel
application/vnd.ms-excel # Excel
application/vnd.openxmlformats-officedocument.wordprocessingml.document  # Word
application/vnd.openxmlformats-officedocument.presentationml.presentation Powerpoint
```
The code was returning `vnd.ms-excel ` as the extension for example and since that's not `xlsx` we …
=> Fix File Icons

backend/chainlit/user_session.py
This is a simple, non-breaking feature `SessionAccessor`, that acts as a wrapper with generic type safety, around the values stored with `user_session`. It does not modify the existing functionality except for adding a `create_accessor` helper method in the `UserSession` class. The core functionality is not touched and should lead to cleaner code, fewer runtime errors, and more advanced solutions from beginners looking to experiment with `chainlit`.
The `create_accessor` helper method provides a convenient factory pattern directly on the `user_session` object. If preferred, we can remove `create_accessor` from the `UserSession` class and simply rely on the `SessionAccessor` init to create accessor instances.
- Introduced `create_accessor` method in `UserSession` to create typed accessors …
=> feat: add typed session accessors for user session management

backend/chainlit/config.py, backend/chainlit/server.py
Case: I'm building `custom_js` used for chainlit in our project using `vite` and due to certain conditions I can produce only native ECMAScript (JS) module (`<script type="module">`) build. But currently only non-modular scripts can be used in `custom_js`
Solution: allow set attributes for the tags of the `custom_js` or `custom_css` file
=> feature: allow set attributes for the tags of the custom_js or custom_css file

CONTRIBUTING.md, backend/chainlit/data/sql_alchemy.py, backend/chainlit/data/storage_clients/gcs.py
1. GCP creates service account keys in IAM through a JSON file. Currently, the private key is a string in the format of `-----BEGIN PRIVATE KEY-----`. However, when using this private key with the `GCS_PRIVATE_KEY` environment variable, the following error occurs:
```
storage_client = GCSStorageClient(
^^^^^^^^^^^^^^^^^
File "/Library/Python/3.11/lib/python/site-packages/chainlit/data/storage_clients/gcs.py", line 16, in __init__
private_key = base64.b64decode(private_key).decode("utf-8")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/base64.py", line 88, in b64decode
return binascii.a2b_base64(s, strict_mode=validate)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
binascii.Error: Incorrect padding
```
The GCP authentication issue was …
=> fix: GCS private key was in incorrect format

frontend/src/api/index.ts, libs/copilot/src/api.ts, libs/copilot/src/appWrapper.tsx, libs/copilot/src/types.ts, libs/react-client/src/api/index.tsx
This PR introduces a new configuration option: `additionalQueryParamsForAPI` in Copilot settings. This allows passing extra query parameters in API requests to the Chainlit server.
- 🆕 **New copilot setting:** `additionalQueryParamsForAPI`, which accepts key-value pairs.
- 🔗 **Automatic query param injection:** When configured, all API requests from the Copilot client will include these parameters.
- 📌 **Example:** If set as `{ "version": "v3", "region": "europe" }`, API calls will be formatted as:
`/auth/config?version=v3&region=europe`
`/project/settings?version=v3&region=europe`
- When Chainlit backend server is behind the API Gateway which enforce some strict API versioning rules, then this configurable option is savior.
- Improves request tracking and API monitoring. For example, if …
=> feat: support additionalQueryParamsForAPI setting in copilot

backend/chainlit/config.py, frontend/src/components/ButtonLink.tsx, frontend/src/components/header/index.tsx, libs/react-client/src/types/config.ts
Builds on #1836 by adding `display_name` optional. I didn't want to re-use `name` so that this isn't a breaking change. @willydouhard I'm no tailwinds expert so I copied the rendered className from the ReadMe over to ButtonLink. This works, but maybe isn't ideal so feel free to update this PR. Thanks!
**Without display_name (current state)**
```toml
[[UI.header_links]]
name = "Confluence"
icon_url = "https://www.atlassian.com/favicon.ico"
url = "https://www.atlassian.com"
[[UI.header_links]]
name = "Issues"
icon_url = "https://mintlify.s3-us-west-1.amazonaws.com/chainlit-43/_generated/favicon/favicon.ico?v=3"
url = "https://github.com/Chainlit/chainlit/issues"
```
**With display_name**
```toml
[[UI.header_links]]
name = "Confluence"
display_name = "Confluence"
icon_url = …
```
=> Add HeaderLink display_name

backend/chainlit/__init__.py
Hi there,
In trying to use chainlit within our application we realized it will always load `.env` even though we have various `.env` files for our different environments such as `.env.production`. Putting up this small PR so that we can just specify the environment ourselves and hopefully this is an acceptable contribution!
=> Feature: Add custom env file loading

backend/chainlit/config.py
Fixes an issue in #2059 where display_name throws pydantic validation errors when omitted. Setting default to None and move to the end fixes this.
=> fix: Fix display_name in header links

frontend/src/components/ButtonLink.tsx
The PR #2059 introduced an optional display name, however if no display name is provided the style gets a bit bat with too much spacing between icons.
This PR preserves the original style when no display is specified and keeping the proposed style when display is set
Currently after #2059
Original before #2059 and after this PR
=> fix: keep icon style when no display is set

backend/chainlit/data/chainlit_data_layer.py
This pull request addresses a bug in the `ChainlitDataLayer` class, specifically in the `get_thread` method. As pointed out in #2084, when resuming a thread, previous feedback entries were not being loaded from the database.
The `Feedback` table was not being queried at all.
The query used to retrieve steps from the database has been updated to also fetch related entries from the `Feedback` table. The method responsible for creating steps to be included in the thread has been updated accordingly. Now, when reloading a thread, previous feedback for each step is displayed correctly.
=> fix: issue #2084 fetching steps feedbacks in get_thread

backend/chainlit/data/storage_clients/azure_blob.py, backend/chainlit/data/storage_clients/base.py, backend/chainlit/data/storage_clients/gcs.py, backend/chainlit/data/storage_clients/s3.py
The 1-hour expiry time for read-only URLs of elements in a chat leads to unusable URLs. 
Some developers want a way to configure the `EXPIRY_TIME`, see https://discord.com/channels/1088038867602526210/1360221598279536800/1363216725641920825
Initially I thought it'd be a Chainlit config, but I thought it best to have it an environment variable, same as all the storage configurations.
=> feat: expose expiry time as environment variable

backend/chainlit/data/chainlit_data_layer.py, backend/chainlit/data/storage_clients/azure.py, backend/chainlit/data/storage_clients/azure_blob.py, backend/chainlit/data/storage_clients/gcs.py, backend/chainlit/data/storage_clients/s3.py
This small PR resolves the deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
=> Resolve Python Logger warnings

backend/chainlit/emitter.py
This fixes the elements mime type for types like "plain/text" where the mimetype fixing in element.py (send) did not work
=> fix: include mime in element

frontend/src/components/chat/MessageComposer/CommandButtons.tsx
Commands on mobile quickly lead to multiple lines of commands in the UI. It is better to collapse the text and just keep the icon. This PR automatically collapses the text if the screen size is too small.
=> Collapse command buttons to icons for small screens

backend/chainlit/data/chainlit_data_layer.py
Only update SQL metadata field when metadata is not None; otherwise, existing metadata will be overwritten as an empty object ({}).
=> fix: only update metadata field when not None to prevent overwriting with {}

CHANGELOG.md, RELENG.md, backend/chainlit/config.py, backend/chainlit/version.py, backend/pyproject.toml
- #2173 
- #2214 
- #2217 
- #2194 
- #2212 
- #2176 
- #2168 
- #2149 
- #2137 
- #2233 
- #1900 
- #1897 
- #2133 
- #2171 
- #2238 
- #2251 
- #2246 
- #2244 
- #2245 
- #2254
=> chore: prepare release

backend/chainlit/mistralai/__init__.py, backend/chainlit/openai/__init__.py
Due to changes from #2245, the openai and mistralai sub-modules cannot be loaded anymore, as timestamp_utc is not loaded from the chainlit.utils.
These changes correctly import timestamp_utc again.
=> Import timestamp_utc from chainlit.utils

frontend/src/components/chat/Starters.tsx
Match @cl.set_starters functionality in cl.ChatProfile's starters array by allowing more than 4 starters
=> Allow more than 4 starters via cl.ChatProfile

.github/workflows/close_stale.yml, .github/workflows/issues.yml
This pull request adds a new GitHub Actions workflow to automate the management of inactive issues and pull requests. The workflow uses the `actions/stale` action to mark issues and pull requests as stale and close them after a period of inactivity. This runs daily at 01:30 UTC.
* [`.github/workflows/issues.yml`](diffhunk://#diff-25671745f65ff1eb3a5901f4fd263e7a59a36d522abd32b8240832f06e5227e8R1-R28): Introduced a workflow named "Close inactive issues" that runs on a daily schedule and can also be triggered manually. It marks issues and pull requests as stale after 14 days of inactivity and closes them 7 days later, with customizable messages and label configurations.
Initial draft to clean up the 407 issues and 35 PRs. We should probably include tags here to keep some feature request …
=> feat: Add workflow to close old Issues/PRs

frontend/src/components/ui/alert-dialog.tsx, frontend/src/components/ui/dialog.tsx, frontend/src/components/ui/dropdown-menu.tsx, frontend/src/components/ui/popover.tsx, frontend/src/components/ui/select.tsx, frontend/src/components/ui/sheet.tsx
This PR slightly refactors (and supersedes) the changes made in #2262, #2251, #2194, and earlier.
It applies a consistent approach and code style. Logic explanation:
For portals (popups, dialogs, elements that "appear" over the UI):
1. The Copilot root will be used if available.
2. If it's not available, the value will be `undefined` - which makes the previous logic with `x ? y : undefined` redundant. In that case, the default value (`document.body`) will be used by UI framework (Radix), making the recent `|| document.body` fallback also unnecessary.
=> refactor: unify portals (dialogs) rendering in Copilot

frontend/src/components/chat/MessageComposer/index.tsx
This is related to this issue : https://github.com/Chainlit/chainlit/issues/1983
=> feat : Added ability to send empty commands

frontend/src/lib/message.ts
This patch hardens link-generation in `prepareContent` so that any element name—no matter what punctuation it contains—produces a syntactically valid Markdown link.
* Introduced `toSafeLinkTarget()` to properly escape parentheses in the visible text portion when rendering reference links.
* `toSafeLinkTarget()` encodes `(` → `%28` and `)` → `%29` after using `encodeURIComponent`, since those characters are not escaped by default.
* Replaced the previous `replaceAll(' ', '_')` logic with the more robust `toSafeLinkTarget()` helper to ensure all generated link targets are valid.
Names such as  
`"Appendix A) : Survey Results"` broke Markdown rendering:
```markdown
[Appendix A) : Survey Results](Appendix_A)_:_Survey_Results)   ← malformed
````
Unescaped parentheses in the link text and URL …
=> fix(markdown): encode parentheses in link targets for valid rendering

backend/chainlit/data/chainlit_data_layer.py
Original behavior: 
`asyncpg.exceptions.PostgresSyntaxError: syntax error at or near ";"`
Caused by this query:
```
postgres-1    | 2025-07-15 12:26:38.419 UTC [544] STATEMENT:  
postgres-1    |                     INSERT INTO "Thread" ("id")
postgres-1    |                     VALUES ($1)
postgres-1    |                     ON CONFLICT (id) DO UPDATE
postgres-1    |                     SET ;
```
which happens when `update_sets` is empty list. 
After suggested fix there is no query error. This is the new query:
```
postgres-1    | 2025-07-15 12:28:44.355 UTC [562] STATEMENT:  
postgres-1    |                     INSERT INTO "Thread" ("id")
postgres-1    |                     VALUES ($1)
postgres-1    |                     ON CONFLICT (id) DO NOTHING
```
=> fix: postgres query syntax error in data_layer

backend/chainlit/data/dynamodb.py
During thread loading with DynamoDBDataLayer, when using a storage provider, fill the "url" field of an element with the signed url generated by the storage provider.
Closes #1962.
=> fix: generate signed url when loading elements from dynamodb datalayer

backend/chainlit/data/chainlit_data_layer.py
Register signal and atexit handlers to ensure proper asyncpg connection pool
cleanup during application shutdown. Improves resilience against connection
errors and resource leaks.
Fixes #2169
=> fix(data-layer): add graceful shutdown handlers for DB connection cleanup

backend/chainlit/translations/en-US.json, frontend/src/components/WaterMark.tsx
This pull request includes updates to improve the watermark text and simplify the `WaterMark` component by removing unused assets and logic for theme-based logo rendering.
* [`backend/chainlit/translations/en-US.json`](diffhunk://#diff-8589b2dc8a08fcfdc5201d4cb8914a3d60969d81956e489df9c91b181c103496L114-R114): Updated the watermark text to make it more concise, changing "LLMs can make mistakes. Consider checking important information." to "LLMs can make mistakes. Check important info."
* [`frontend/src/components/WaterMark.tsx`](diffhunk://#diff-986041e01dd400bdb966fc76d05cd61fa557fdc2c9663b140accb98288a7c5e3L3-L13): Removed imports for `logo_dark.svg` and `logo_light.svg` assets and the associated logic for rendering theme-based logos. Simplified the component by eliminating the …
=> feat: remove watermark logo

frontend/src/components/Elements/CustomElement/index.tsx, frontend/src/components/WaterMark.tsx, frontend/src/components/chat/MessageComposer/Mcp/index.tsx, frontend/src/components/chat/Messages/Message/Avatar.tsx, frontend/src/lib/message.ts, libs/copilot/src/components/Header.tsx, libs/copilot/src/widget.tsx, libs/react-client/src/useChatSession.ts
- Prevents an unnecessary call to the `/logo` endpoint on first render by preloading project settings when Copilot initializes
- Applies Prettier formatting to maintain consistent code style.
- On initial load, Copilot was making a redundant request to `/logo`, even when `logo_file_url` was already configured. This PR ensures that project settings are fetched early, so unnecessary network calls are avoided, [read more about the issue.](https://github.com/Chainlit/chainlit/issues/2339)
- Configure `logo_file_url` (under UI section) in `config.toml` file
- Run the chainlit server locally, and [create a test site to use copilot mode.](https://docs.chainlit.io/deploy/copilot#embedding-the-copilot)
- Click the copilot icon to open the chat.
- Confirm that no request to `/logo` is made
- Check …
=> fix: avoid /logo call if logo_file_url is set

.github/actions/pnpm-node-install/action.yaml
This PR brings back `pnpm` caching after #2257 and extends it to include the `libs/` folder with the shared `react-client` and `copilot` libraries. CI should run a bit faster as a result.
=> ci: bring back pnpm cache

backend/chainlit/server.py
This PR reduces the frontend bundle size from 3.7 MB to 1 MB and partially addresses #2340. A proper fix would involve improving tree shaking and chunk splitting in the frontend, but that would require additional configuration and possibly some refactoring.
=> feat: enable gzip compression for frontend

frontend/src/components/chat/MessageComposer/Input.tsx
Fixes #2326, proper implementation of #2267 and #2246, related to #2264
=> fix: properly escape html on paste

cypress/e2e/data_layer/spec.cy.ts
Somewhere in #2327, my revert commit for the temporarily skipped test was missed. This PR restores that test.
=> test: restore temporarily skipped test

backend/chainlit/config.py, libs/react-client/src/types/config.ts
Instead of `font_family`, `custom_fonts` + separate `--font-*` css variables used in `public/theme.json` as described in [Chainlit](https://docs.chainlit.io/customisation/theme) and [Shadecdn](https://ui.shadcn.com/docs/theming#list-of-variables) documentation, but this setting wasn't removed
Tested with #2368 just in case, please merge it first
=> refactor: remove unused font_family from configuration

.gitignore, cypress/e2e/custom_build/.chainlit/config.toml, cypress/e2e/custom_build/.gitignore, cypress/e2e/user_env/.chainlit/config.toml, cypress/e2e/user_env/.gitignore
- Return meaningful configs to e2e tests
- Fixed `.gitignore` to locally exclude meaningful configs from removal
Should fix CI after #2368
=> test: return meaningful configs to e2e tests

frontend/src/components/Markdown.tsx
This reverts commit 63a0b202967a8d18626cc17d2ed2dbfe3413fb5c.
This PR reverts a part of solution for #2367 and closes #2375.
Ignoring of some line breaks and removal of leading whitespaces [are part of Markdown](https://github.com/orgs/remarkjs/discussions/1194).
User messages rendered as Markdown by both Chainlit and all popular LLM chats.
All future issues about that should be closed with resolution `won't fix`
=> Revert "fix: preserve line breaks in received messages (#2372)"

cypress/e2e/blinking_cursor/main.py, cypress/e2e/blinking_cursor/spec.cy.ts, frontend/src/components/chat/Messages/index.tsx
This should fix: https://github.com/Chainlit/chainlit/issues/2376
=> feat: bring back blinking cursor indicating activity

backend/chainlit/server.py
=> fix: disable gzip for websocket-related http endpoints due to bug in Safari

backend/chainlit/emitter.py, backend/chainlit/server.py, backend/chainlit/session.py, backend/tests/conftest.py, backend/tests/test_server.py, cypress/e2e/ask_file/main.py, cypress/e2e/ask_multiple_files/main.py, frontend/src/components/chat/Messages/Message/AskFileButton.tsx, frontend/src/components/chat/MessagesContainer/index.tsx, libs/react-client/src/api/index.tsx, libs/react-client/src/useChatInteract.ts
This a follow up of https://github.com/Chainlit/chainlit/issues/1658.
This PR solve :
- the validate_file_upload() that prevented uploading file with AskFileMessage when spontaneous_file_upload was set to False
- the POST /project/file will now validate the upload against the AskFileMessage limit/accept instead of the spontaneous upload limit/accept (fallback to spontaneous limits if not provided)
=> fix: AskFileButton can now upload file with proper checking and it's own limits

backend/chainlit/auth/__init__.py, backend/chainlit/cli/__init__.py, cypress/e2e/chat_profiles/main.py, cypress/e2e/config_overrides/main.py, cypress/e2e/custom_data_layer/sql_alchemy.py, cypress/e2e/data_layer/main.py, cypress/e2e/header_auth/main.py, cypress/e2e/password_auth/main.py
Currently, enabling authentication in Copilot requires setting **two** environment variables:  
- `CHAINLIT_AUTH_SECRET`  
- `CHAINLIT_CUSTOM_AUTH=true` (undocumented)  
See: [chainlit/chainlit#2190](https://github.com/Chainlit/chainlit/issues/2190)
Requiring `CHAINLIT_CUSTOM_AUTH` is unnecessary and not documented, which can lead to confusion for users.
Remove the `CHAINLIT_CUSTOM_AUTH` check and rely solely on the presence of `CHAINLIT_AUTH_SECRET` to enable authentication.
=> feat(auth): update require_login to check for CHAINLIT_AUTH_SECRET environment variable instead of CHAINLIT_CUSTOM_AUTH

backend/chainlit/translations/es.json
This PR adds `backend/chainlit/translations/es.json` using neutral Spanish, suitable as a fallback for all Spanish-speaking regions.
When using variants (like es-419), the app logs:
`Translation file for es-419 not found. Using parent translation es.`
Since the fallback is intentional and the translation is neutral, suppressing this log for Spanish could be a good improvement, or I could also just add the variants as their own file, though they wil all have the same content. Let me which approach is preferred.
=> feat: add Spanish translation file

backend/chainlit/socket.py
The audio handlers were using the global config instead of the overrides from the chat_profile
=> fix: take overridden config into account in audio handlers

backend/chainlit/server.py
I want to allow admins to view any threads.  I determine if a user is an admin using custom RBAC roles and saving in the user.metadata. Presumably other developers will have other ways of doing this.
This change makes it so that as long as the `@cl.on_shared_thread_view` returns True then the thread can be viewed, instead of requiring the user to share the thread. Developers can customize the logic within this callback however they see fit.
=> refactor: allow Thread Sharing by user-defined callback

frontend/src/components/chat/MessageComposer/VoiceButton.tsx
The voice activation hotkey ('P') was incorrectly triggering when typing in the chat input field within the copilot widget, while working correctly in the main frontend application.
The copilot widget renders components inside a Shadow DOM for isolation from the host page. The `react-hotkeys-hook` library's default focus detection mechanism (`document.activeElement`) doesn't work correctly across Shadow DOM boundaries, causing it to miss when form fields inside the Shadow DOM are focused.
Implemented Shadow DOM-aware focus detection in the `VoiceButton` component:
- **Deep Active Element Detection**: Added a recursive function `getDeepActiveElement()` that traverses through Shadow DOM boundaries to find the actually focused element
- **Runtime Focus Check**: Added a check within the …
=> fix(copilot): Voice hotkey (P) incorrectly triggers when typing in chat input within Shadow DOM

.github/actions/pnpm-node-install/action.yaml, .github/workflows/ci.yaml, .github/workflows/copilot-setup-steps.yaml, .github/workflows/e2e-tests.yaml, .github/workflows/publish-libs.yaml, .github/workflows/publish.yaml, RELENG.md, libs/react-client/package.json, package.json
Closes #2550
This PR enables automatic publishing of the `@chainlit/react-client` (and any other non-private package in `libs/*` if we will add them) to the **npm** registry.
To test the publishing process, use the **Dry run (test publishing)** option, similar to the **Publish to TestPyPI instead of PyPI** feature introduced in #2483.
- Removed `pnpm install` arguments, since CI **must always use a frozen lockfile**.
* **Updating the lockfile during CI runs is bad practice**, as changes are not committed back to the repository and resolved dependency versions may differ from those declared in the source code.
* If you encounter an error where `pnpm` indicates that the lockfile needs to be updated, run `pnpm install` or `pnpm install --lockfile-only` locally and commit the resulting …
=> ci: libs publishing workflow
